import {customArrangement} from './ui-helpers'
import {previewAdminSave} from './ui-helpers'
import {API_BASE} from './api-base'
import {test,expect} from '@playwright/test'
import {mkdtempSync,writeFileSync,mkdirSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {spawn,type ChildProcess} from 'node:child_process'
import {publishFixture,enter,tab,save,close,adminSession} from './activity-fixture'
let server:ChildProcess
const base='http://localhost:5174'
test.beforeAll(async()=>{const directory=mkdtempSync(join(tmpdir(),'tongye-activity-sw-'));const build=spawn(process.execPath,['node_modules/vite/bin/vite.js','build','--outDir',directory],{env:{...process.env,VITE_API_URL:`${API_BASE}`},stdio:['ignore','pipe','pipe']});let output='';build.stdout?.on('data',chunk=>output+=chunk);build.stderr?.on('data',chunk=>output+=chunk);await new Promise<void>((resolve,reject)=>{build.on('exit',code=>code===0?resolve():reject(new Error('Isolated production build failed')));build.on('error',reject)});writeFileSync('/tmp/tongye-activity-sw-build.log',output);server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','5174','--strictPort','--outDir',directory],{stdio:'ignore'});for(let i=0;i<100;i++){try{if((await fetch(base)).ok)return}catch{}await new Promise(resolve=>setTimeout(resolve,200))}throw new Error('Local production preview did not start')},60000)
test.afterAll(async()=>{server?.kill('SIGTERM')})
test('实际SW离线刷新活动、图片与个人草稿；重连版本改变不覆盖',async({browser})=>{test.setTimeout(90000);const pack=await publishFixture(browser,'offline',base),context=await browser.newContext({viewport:{width:390,height:900},serviceWorkers:'allow'}),page=await context.newPage();await enter(page,pack,base);await page.evaluate(()=>navigator.serviceWorker.ready);if(!await page.evaluate(()=>!!navigator.serviceWorker.controller))await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await tab(page,'计划');await page.getByRole('button',{name:'日程',exact:true}).click();await customArrangement(page);await page.getByRole('dialog').getByLabel('活动名').fill('离线分钟草稿');await page.getByRole('dialog').getByLabel('开始时间',{exact:true}).fill('13:07');await page.getByRole('dialog').getByLabel('结束时间',{exact:true}).fill('13:52');await page.getByRole('dialog').getByRole('button',{name:'加入计划',exact:true}).click();await save(page);await tab(page,'我的');await page.getByRole('button',{name:'为现场准备离线数据'}).click();await expect(page.getByRole('dialog')).toContainText(/预计下载|地图大小暂时未知/);await page.getByRole('button',{name:'准备所选资料'}).click();await expect(page.locator('p[role=status]')).toContainText('离线资料已准备');await context.setOffline(true);await page.unroute('**/api/media/read?**');await page.getByLabel('个人称呼').fill('离线修改保留');await page.reload();await tab(page,'我的');await expect(page.getByLabel('个人称呼')).toHaveValue('离线修改保留');await tab(page,'探索');await page.getByRole('button',{name:'地图',exact:true}).click();await expect(page.getByRole('group',{name:'活动地图，可平移与缩放'})).toBeVisible();await expect(page.locator('svg image')).toHaveAttribute('href',/^blob:/);await tab(page,'计划');await page.getByRole('button',{name:'日程',exact:true}).click();await expect(page.locator('.sched-row').filter({hasText:'离线分钟草稿'})).toContainText('13:07');await page.getByRole('button',{name:'保存个人计划',exact:true}).click();await expect(page.locator('p[role=status]')).toContainText(/本机|连接失败|未联网/);
 const admin=await browser.newContext(),manager=await admin.newPage();await manager.goto(base+'/admin');await manager.getByLabel('管理员密码').fill('a'.repeat(64));await manager.getByRole('button',{name:'进入管理'}).click();await manager.getByRole('button',{name:new RegExp(pack.event.title)}).click();await manager.getByRole('dialog').getByRole('button',{name:'导入或导出活动文件'}).click();const changed=structuredClone(pack);changed.event.activities[0].sessions[1].start='13:08';await manager.getByLabel('或粘贴 JSON').fill(JSON.stringify(changed));await manager.getByRole('button',{name:'校验并使用'}).click();await previewAdminSave(manager);await manager.getByRole('button',{name:'确认保存'}).click();await expect(manager.getByRole('dialog')).toHaveCount(0);await context.setOffline(false);await page.reload();await tab(page,'计划');const response=page.waitForResponse(r=>r.request().method()==='PUT'&&/\/personal\//.test(r.url()));await page.getByRole('button',{name:'保存个人计划',exact:true}).click();expect((await response).status()).toBe(409);await tab(page,'我的');await expect(page.getByLabel('个人称呼')).toHaveValue('离线修改保留');await page.getByRole('button',{name:'恢复与导出'}).click();await expect(page.getByRole('button',{name:'已核对，保留草稿'})).toBeVisible();await close(page);await admin.close();await context.close()
})

// Selection uses an atomic record of the complete activity plus the chosen map blobs.
test('离线准备可只选一图，未下载地图明确失败而列表与原地图可继续使用',async({browser,request})=>{
 const pack=await publishFixture(browser,'offline-selection',base),next=structuredClone(pack);next.event.extensions!.convention.maps.push({...next.event.extensions!.convention.maps[0],id:'second-map',title:'虚构二区地图'});const token='f'.repeat(64);await adminSession(request,token);const response=await request.post(`${API_BASE}/api/v1/admin/events`,{headers:{Authorization:'Bearer '+token},data:{eventPackage:next,status:'published',expectedRevision:2,operationId:crypto.randomUUID()}});expect(response.status()).toBe(200)
 const context=await browser.newContext({viewport:{width:390,height:900},serviceWorkers:'allow'}),page=await context.newPage();await enter(page,pack,base);await page.evaluate(()=>navigator.serviceWorker.ready);if(!await page.evaluate(()=>!!navigator.serviceWorker.controller))await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await tab(page,'我的');await page.getByRole('button',{name:'为现场准备离线数据'}).click();await page.getByLabel('下载 虚构二区地图').uncheck();await expect(page.getByLabel('下载 虚构二区地图')).not.toBeChecked();await expect.poll(()=>page.getByRole('dialog').evaluate(e=>Math.round(e.getBoundingClientRect().bottom))).toBe(900);mkdirSync('/tmp/tongye-browse-tools-evidence',{recursive:true});await page.screenshot({path:'/tmp/tongye-browse-tools-evidence/offline-selection-390-light.png',animations:'disabled'});await expect(page.getByRole('dialog')).toContainText('资料版本 3');await page.getByRole('button',{name:'准备所选资料'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('p[role=status]')).toContainText('1 张地图')
 const ids=await page.evaluate(async id=>new Promise<string[]>((resolve,reject)=>{const r=indexedDB.open('coukong-online-v1',1);r.onsuccess=()=>{const get=r.result.transaction('records').objectStore('records').get(`activity-prepared:v1:${id}:public`);get.onsuccess=()=>{resolve(get.result.maps.map((m:{mapId:string})=>m.mapId));r.result.close()};get.onerror=()=>reject(get.error)}}),pack.event.id);expect(ids).toEqual(['demo-map']);await context.setOffline(true);await page.unroute('**/api/media/read?**');await tab(page,'探索');await page.getByRole('button',{name:'地图',exact:true}).click();await page.getByLabel('地图区域').selectOption('second-map');await expect(page.getByText('这张地图未下载，请联网后重新准备',{exact:true})).toBeVisible();await expect(page.locator('svg image')).toHaveCount(0);await page.getByRole('button',{name:'列表',exact:true}).click();await expect(page.locator('.sched-row').filter({hasText:'示例地点 A'})).toBeVisible();await page.getByRole('button',{name:'地图',exact:true}).click();await page.getByLabel('地图区域').selectOption('demo-map');await expect(page.locator('svg image')).toHaveAttribute('href',/^blob:/);await context.close()
})
