import {customArrangement} from './ui-helpers'
import {test,expect} from '@playwright/test'
import {mkdirSync} from 'node:fs'
import {download} from './ui-helpers'
import {close,tab,imageFixture,publishFixture,enter,save} from './activity-fixture'
const evidence='/tmp/tongye-activity-user-evidence';mkdirSync(evidence,{recursive:true})
// Activity/media metadata and private plans are persisted in real isolated D1.
// Images are fixed local PNG responses, NOT a claim of Blob upload/deployment.
test('不组队收藏、分钟个人计划、路线与草稿冲突保留真实闭环',async({browser})=>{test.setTimeout(90000);const pack=await publishFixture(browser,'core');const context=await browser.newContext({viewport:{width:390,height:900}}),page=await context.newPage();await enter(page,pack);await page.locator('.sched-row').filter({hasText:'示例地点 A'}).click();let d=page.getByRole('dialog',{name:'示例地点 A'});await d.getByRole('button',{name:'收藏',exact:true}).click();await d.getByRole('button',{name:'加入路线',exact:true}).click();await close(page);await tab(page,'计划');await page.getByRole('button',{name:'日程',exact:true}).click();await expect(page.getByText('当天还没有安排',{exact:true})).toBeVisible();await page.getByRole('button',{name:/本日在场时间/}).click();d=page.getByRole('dialog');await d.getByLabel('开始时间 1',{exact:true}).fill('13:00');await d.getByLabel('结束时间 1',{exact:true}).fill('18:00');await d.getByRole('button',{name:'保存',exact:true}).click();await customArrangement(page);d=page.getByRole('dialog',{name:'个人安排'});await d.getByLabel('活动名').fill('分钟个人计划');await d.getByLabel('开始时间',{exact:true}).fill('13:07');await d.getByLabel('结束时间',{exact:true}).fill('13:52');await d.getByLabel('私密备注').fill('仅本人可读');await d.getByRole('button',{name:'加入计划',exact:true}).click();await save(page);await page.reload();await page.getByRole('button',{name:'日程',exact:true}).click();await expect(page.locator('.sched-row').filter({hasText:'分钟个人计划'})).toContainText('13:07');await tab(page,'我的');await page.getByRole('button',{name:'恢复与导出'}).click();const exported=JSON.parse(await download(page,'导出个人计划'));expect(exported.plan.response.busy[0]).toMatchObject({start:'13:07',end:'13:52',note:'仅本人可读'});expect(exported.plan.favorites).toHaveLength(1);expect(exported.plan.routes[0].stops).toHaveLength(1);expect(JSON.stringify(exported)).not.toMatch(/token|Bearer|coukong-admin/);const recovery=await download(page,'保存个人恢复链接');await close(page);const other=await browser.newContext(),second=await other.newPage();await imageFixture(second);await second.goto(recovery);await tab(second,'我的');await second.getByLabel('个人称呼').fill('另一设备草稿');await tab(page,'我的');await page.getByLabel('个人称呼').fill('设备一更新');await tab(page,'计划');await save(page);await tab(second,'计划');const conflict=second.waitForResponse(r=>r.request().method()==='PUT'&&/\/personal\//.test(r.url()));await second.getByRole('button',{name:'保存个人计划',exact:true}).click();expect((await conflict).status()).toBe(409);await second.reload();await tab(second,'我的');await expect(second.getByLabel('个人称呼')).toHaveValue('另一设备草稿');await other.close();await context.close()})

for(const width of [375,390,430,1440])test(`活动用户真实内容${width}浅深屏`,async({browser})=>{test.setTimeout(60000);const pack=await publishFixture(browser,`gallery-${width}`);for(const scheme of ['light','dark'] as const){const context=await browser.newContext({viewport:{width,height:900},colorScheme:scheme}),page=await context.newPage();await imageFixture(page);await page.goto('/');const listed=page.locator('.sched-row').filter({hasText:pack.event.title}).first();await expect(listed).toBeVisible();const title=(await listed.locator('.sched-title').boundingBox())!,meta=(await listed.locator('.sched-meta').boundingBox())!;expect(meta.y).toBeGreaterThanOrEqual(title.y+title.height-1);expect(title.x+title.width).toBeLessThanOrEqual(width);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({animations:'disabled',path:`${evidence}/list-${width}-${scheme}.png`});await enter(page,pack);if(width<900)await page.getByRole('button',{name:'地图',exact:true}).click();const svg=page.getByRole('group',{name:'活动地图，可平移与缩放'});await expect(svg).toBeVisible();await page.screenshot({animations:'disabled',path:`${evidence}/map-${width}-${scheme}.png`});if((page.viewportSize()?.width||0)<900)await page.getByRole('button',{name:'列表',exact:true}).click();await page.locator('.sched-row').filter({hasText:'示例地点 A'}).click();await expect(page.getByRole('dialog')).toContainText('测试标签');await expect.poll(()=>page.getByRole('dialog').evaluate(e=>Math.round(e.getBoundingClientRect().bottom))).toBe(900);await page.screenshot({animations:'disabled',path:`${evidence}/poi-${width}-${scheme}.png`});await close(page);await page.locator('.sched-row').filter({hasText:'13:07'}).click();await page.getByRole('button',{name:'加入计划',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await tab(page,'计划');await page.getByRole('button',{name:'日程',exact:true}).click();await expect(page.getByRole('button',{name:'日程',exact:true})).toHaveClass('on');await expect(page.locator('.sched-row')).toContainText('13:07');await page.screenshot({animations:'disabled',path:`${evidence}/plan-${width}-${scheme}.png`});await tab(page,'同行');await expect(page.locator('.figma-companions-entry')).toBeVisible();await expect(page.getByRole('button',{name:'创建',exact:true})).toBeVisible();await expect(page.getByLabel('小队邀请链接')).toBeVisible();await page.screenshot({animations:'disabled',path:`${evidence}/companions-${width}-${scheme}.png`});await tab(page,'我的');await expect(page.getByRole('button',{name:'为现场准备离线数据'})).toBeVisible();await page.screenshot({animations:'disabled',path:`${evidence}/me-${width}-${scheme}.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await context.close()}})

test('首次个人身份慢响应期间保存，等待同一身份后成功提交草稿',async({browser})=>{
 const pack=await publishFixture(browser,'slow-personal-create'),context=await browser.newContext({viewport:{width:390,height:900}}),page=await context.newPage()
 let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve});let started!:()=>void;const observed=new Promise<void>(resolve=>{started=resolve})
 await page.route('**/api/v1/events/*/personal',async route=>{if(route.request().method()!=='POST')return route.continue();const response=await route.fetch();started();await gate;await route.fulfill({response})})
 await enter(page,pack);await page.locator('.sched-row').filter({hasText:'示例地点 A'}).click();await page.getByRole('dialog').getByRole('button',{name:'收藏',exact:true}).click();await observed
 await close(page);await tab(page,'计划');const submitted=page.waitForResponse(r=>r.request().method()==='PUT'&&/\/personal\//.test(r.url()))
 await page.getByRole('button',{name:'保存个人计划',exact:true}).click();release();expect((await submitted).status()).toBe(200);await expect(page.locator('p[role=status]')).toContainText('已保存到云端')
 await page.reload();await tab(page,'计划');await page.getByRole('button',{name:'收藏',exact:true}).click();await expect(page.getByRole('button',{name:'示例地点 A',exact:true})).toBeVisible();await context.close()
})
