import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {create,join,presence,busy,settings,submit,tab,personal,manager,download,importEvent,review,closeSheet,action} from './ui-helpers'
test('三个独立身份：真实D1、分钟、状态、导入、离线与并发',async({browser})=>{
 const contexts=await Promise.all([browser.newContext(),browser.newContext(),browser.newContext()]);const [owner,a,b]=await Promise.all(contexts.map(c=>c.newPage()));const invite=await create(owner,'本地真实三人验收',undefined,'09:00','18:00');await join(a,invite,'A');await join(b,invite,'B');await tab(owner,'小队日程');await owner.getByLabel('怎么称呼').fill('发起人');await owner.getByRole('button',{name:'加入小队',exact:true}).click();await presence(owner,'09:00','18:00');await submit(owner);await tab(owner,'共同空闲');await owner.getByRole('button',{name:'刷新',exact:true}).click();await expect(owner.getByText(/等待.*A.*B.*提交/)).toBeVisible();
 await presence(a,'09:00','12:00');await settings(a,{buffer:5});await busy(a,'A私密忙碌','10:07','10:22','只有A可读的私密备注');await submit(a);await presence(b,'09:15','11:50');await busy(b,'B忙碌','09:40','09:55');await submit(b);await owner.getByRole('button',{name:'刷新',exact:true}).click();await owner.getByRole('button',{name:'5 分钟以上',exact:true}).click();for(const s of ['09:15–09:40','09:55–10:02','10:27–11:50'])await expect(owner.locator('.free-range').filter({hasText:s})).toBeVisible();await expect(owner.getByText('只有A可读的私密备注')).toHaveCount(0);await owner.getByRole('button',{name:'15 分钟以上',exact:true}).click();await expect(owner.getByText('09:55–10:02',{exact:true})).toHaveCount(0);
 await busy(a,'分钟精度','13:07','13:52');await settings(a,{step:'5'});await submit(a);await a.reload();await expect(a.locator('.sched-row').filter({hasText:'分钟精度'})).toContainText('13:07');await personal(a);const personalData=JSON.parse(await download(a,'导出个人安排'));expect(personalData.response.busy.find((x:{title:string})=>x.title==='分钟精度')).toMatchObject({start:'13:07',end:'13:52'});const recovery=await download(a,'保存我的恢复链接');await closeSheet(a);const duplicateContext=await browser.newContext(),duplicate=await duplicateContext.newPage();await duplicate.goto(recovery);await expect(duplicate.getByRole('button',{name:'日程设置'})).toBeVisible();await settings(a,{name:'A更新'});await submit(a);await settings(duplicate,{name:'A冲突草稿'});await submit(duplicate,409);await expect(duplicate.locator('.overview')).toContainText('A冲突草稿');
 await contexts[1].setOffline(true);await settings(a,{name:'A离线草稿'});await a.getByRole('button',{name:'提交',exact:true}).click();await expect(a.locator('.page-sub[role=status]')).toContainText(/未联网|未提交/);await contexts[1].setOffline(false);await a.reload();await expect(a.locator('.overview')).toContainText('A离线草稿');const pack=JSON.parse(readFileSync('examples/event-demo.json','utf8'));await importEvent(owner,pack);await tab(owner,'成员');await expect(owner.locator('.me-row').filter({hasText:'B'})).toContainText('需要重新确认');await manager(owner);expect(JSON.parse(await download(owner,'导出活动 JSON'))).toEqual(pack);await closeSheet(owner);
 await tab(b,'共同空闲');await b.getByRole('button',{name:'刷新',exact:true}).click();await tab(b,'小队日程');await review(b);await b.getByRole('button',{name:'手动添加',exact:true}).click();await b.getByRole('dialog',{name:'安排',exact:true}).getByRole('button',{name:'13:07–13:52',exact:true}).click();await expect(b.getByRole('dialog')).toHaveCount(0);await submit(b);const changed=structuredClone(pack);changed.event.activities[0].sessions[1].start='13:08';await importEvent(owner,changed);await tab(b,'共同空闲');await b.getByRole('button',{name:'刷新',exact:true}).click();await tab(b,'小队日程');await expect(b.locator('.sched-row').filter({hasText:'手作体验示例'})).toContainText('新时间 2026-10-03 13:08–13:52');await expect(b.locator('.sched-row').filter({hasText:'手作体验示例'})).toContainText('13:07');await owner.goto('/?legacy=1');await owner.emulateMedia({reducedMotion:'reduce'});await owner.keyboard.press('Tab');expect(await owner.evaluate(()=>document.activeElement?.tagName)).not.toBe('BODY');for(const width of [375,390,430,1440]){await owner.setViewportSize({width,height:900});expect(await owner.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}await duplicateContext.close();await Promise.all(contexts.map(c=>c.close()));
})
test('站内帮助与真实示例下载',async({page})=>{await page.goto('/help/');await expect(page.locator('body')).toContainText('邀请');expect(await (await page.request.get('/examples/event-demo.json')).text()).toBe(readFileSync('examples/event-demo.json','utf8'));await page.goto('/help/event-json/');await expect(page.locator('body')).toContainText('JSON')})
test('旧本机原文保护、首屏hydration与静态入口',async({page})=>{const raw=JSON.stringify({state:{profile:{name:'旧本人'},bookings:[{day:'10-03',start:'13:07',end:'13:52',title:'旧安排'}],friends:[{name:'旧朋友'}]},version:0});await page.addInitScript(value=>localStorage.setItem('coukong',value),raw);await page.goto('/?legacy=1');await page.getByText('旧版数据与备份',{exact:true}).click();await (await action(page,'下载旧数据原文')).waitFor({state:'visible'});expect(await download(page,'下载旧数据原文')).toBe(raw);expect(await page.evaluate(()=>localStorage.getItem('coukong'))).toBe(raw);await expect(page.getByRole('button',{name:'小队 →'})).toHaveCount(0)})
