import {API_BASE,PRODUCTION_BASE,PRODUCTION_PORT} from './api-base'
import {test,expect} from '@playwright/test'
import {build,preview,type PreviewServer} from 'vite'
import {mkdtempSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join as joinPath} from 'node:path'
import {create,join,presence,submit,settings,tab,manager,download,importEvent,closeSheet} from './ui-helpers'
let server:PreviewServer;const output=mkdtempSync(joinPath(tmpdir(),'coukong-pwa-e2e-'))
test.beforeAll(async()=>{process.env.VITE_API_URL=`${API_BASE}`;await build({build:{outDir:output,emptyOutDir:false},logLevel:'warn'});server=await preview({build:{outDir:output},preview:{host:'127.0.0.1',port:PRODUCTION_PORT,strictPort:true},logLevel:'warn'})},120000)
test.afterAll(async()=>{if(!server)return;server.httpServer.closeAllConnections();await new Promise<void>(resolve=>server.httpServer.close(()=>resolve()));console.log(`Production PWA test build retained at ${output}`)})
async function setup(browser:import('@playwright/test').Browser,sw:'allow'|'block'='allow'){const ownerContext=await browser.newContext({serviceWorkers:sw}),memberContext=await browser.newContext({serviceWorkers:sw});const owner=await ownerContext.newPage(),member=await memberContext.newPage();const link=await create(owner,'离线刷新回归',PRODUCTION_BASE);await join(member,link,'离线成员');await presence(member,'13:07','13:52');await submit(member);return {ownerContext,memberContext,owner,member}}
test('生产SW真实离线刷新恢复草稿，重连活动版本变化拒绝旧草稿',async({browser})=>{const {ownerContext,memberContext,owner,member}=await setup(browser);await member.evaluate(async()=>{await navigator.serviceWorker.ready});await member.reload();await expect(member.locator('.overview')).toContainText('离线成员');expect(await member.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await memberContext.setOffline(true);await settings(member,{name:'离线修改保留'});await member.reload();await expect(member.locator('.overview')).toContainText('离线修改保留');await expect(member.getByRole('button',{name:/本日在场时间/})).toContainText('13:07–13:52');await manager(owner);const pack=JSON.parse(await download(owner,'导出活动 JSON'));await closeSheet(owner);pack.event.days[0].openIntervals[0].end='19:00';await importEvent(owner,pack);await memberContext.setOffline(false);await tab(member,'共同空闲');await member.getByRole('button',{name:'刷新',exact:true}).click();await tab(member,'小队日程');await expect(member.getByRole('button',{name:'核对安排'})).toBeVisible();await submit(member,409);await expect(member.locator('.overview')).toContainText('离线修改保留');await member.reload();await expect(member.locator('.overview')).toContainText('离线修改保留');await ownerContext.close();await memberContext.close()})
test('慢PUT期间新编辑保留，交错小队与结果版本拒绝混合刷新',async({browser})=>{const {ownerContext,memberContext,owner,member}=await setup(browser,'block');let release!:()=>void,arrived!:()=>void;const waiting=new Promise<void>(resolve=>release=resolve),seen=new Promise<void>(resolve=>arrived=resolve);await member.route('**/members/*/response',async route=>{if(route.request().method()==='PUT'){arrived();await waiting}await route.continue()});await settings(member,{name:'慢请求提交内容'});await member.getByRole('button',{name:'提交',exact:true}).click();await seen;await settings(member,{name:'提交中继续编辑'});const delayed=member.waitForResponse(r=>r.url().endsWith('/response')&&r.request().method()==='PUT');release();expect((await delayed).status()).toBe(200);await expect(member.getByRole('button',{name:'提交',exact:true})).toBeEnabled();await member.reload();await expect(member.locator('.overview')).toContainText('提交中继续编辑');await member.unroute('**/members/*/response');await submit(member);await tab(member,'共同空闲');const fetch=member.waitForResponse(r=>r.url().endsWith('/availability'));await member.getByRole('button',{name:'刷新',exact:true}).click();const stale=await (await fetch).json();await manager(owner);const pack=JSON.parse(await download(owner,'导出活动 JSON'));await closeSheet(owner);pack.event.days[0].openIntervals[0].end='18:00';await importEvent(owner,pack);await member.route('**/availability',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(stale)}));await member.getByRole('button',{name:'刷新',exact:true}).click();await expect(member.getByRole('alert').filter({hasText:'活动资料正在更新，请稍后刷新'})).toBeVisible();await tab(member,'小队日程');await manager(owner);expect(JSON.parse(await download(owner,'导出活动 JSON')).event.days[0].openIntervals[0].end).toBe('18:00');await closeSheet(owner);await ownerContext.close();await memberContext.close()})
test('新安排未按保存：真实离线刷新恢复editor草稿且不产生幽灵安排',async({browser})=>{const {ownerContext,memberContext,member}=await setup(browser);await member.evaluate(async()=>{await navigator.serviceWorker.ready});await member.reload();await expect(member.getByRole('button',{name:'手动添加'})).toBeVisible();await member.getByRole('button',{name:'手动添加'}).click();const editor=member.getByRole('dialog',{name:'安排',exact:true});await editor.getByLabel('活动名').fill('未保存离线安排');await editor.getByLabel('开始时间',{exact:true}).fill('13:07');await editor.getByLabel('结束时间',{exact:true}).fill('13:52');await editor.getByLabel('私密备注').fill('仅本机编辑草稿');await closeSheet(member);await expect(member.locator('.sched-row')).toHaveCount(0);await memberContext.setOffline(true);await member.reload();await member.getByRole('button',{name:'手动添加'}).click();await expect(editor.getByLabel('活动名')).toHaveValue('未保存离线安排');await expect(editor.getByLabel('开始时间',{exact:true})).toHaveValue('13:07');await expect(editor.getByLabel('结束时间',{exact:true})).toHaveValue('13:52');await expect(editor.getByLabel('私密备注')).toHaveValue('仅本机编辑草稿');await closeSheet(member);await expect(member.locator('.sched-row')).toHaveCount(0);await memberContext.setOffline(false);await member.getByRole('button',{name:'手动添加'}).click();await editor.getByRole('button',{name:'保存',exact:true}).click();await expect(editor).toHaveCount(0);await expect(member.locator('.sched-row')).toContainText('未保存离线安排');await submit(member);await ownerContext.close();await memberContext.close()})
