import {API_BASE} from './api-base'
import {test,expect} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
import {enter,publishFixture,tab,close,save} from './activity-fixture'
import {download} from './ui-helpers'
const base=process.env.TONGYE_E2E_BASE_URL||'http://localhost:5173'
const evidence='/tmp/tongye-personal-tools-evidence';mkdirSync(evidence,{recursive:true})
test('活动类型与状态筛选、资料更新时间',async({page})=>{
 const pkg=JSON.parse(readFileSync('examples/event-minimal.json','utf8'))
 const values=[{id:'list-generic',revision:1,scheduleRevision:1,spatialRevision:1,status:'published',updatedAt:'2026-09-30T10:00:00Z',eventPackage:pkg},{id:'list-comic',revision:1,scheduleRevision:1,spatialRevision:1,status:'cancelled',updatedAt:'2026-09-30T10:00:00Z',eventPackage:{...pkg,event:{...pkg.event,title:'取消的漫展',eventType:'comic_convention'}}}]
 await page.route('**/api/v1/events',r=>r.fulfill({json:{data:values}}));await page.goto(base)
 await expect(page.getByText('资料更新：2026-09-30 18:00',{exact:false})).toHaveCount(2)
 await expect(page.getByRole('heading',{name:'选择活动',exact:true})).toBeVisible()
 await page.getByLabel('活动类型').getByRole('button',{name:'展会',exact:true}).click();await expect(page.locator('.activity-list-group .sched-row')).toHaveCount(1)
 await page.getByLabel('日期状态').selectOption('cancelled');await expect(page.locator('.activity-list-group')).toContainText('取消的漫展')
 await page.getByLabel('活动类型').getByRole('button',{name:'活动',exact:true}).click();await expect(page.getByText('没有匹配的活动',{exact:true})).toBeVisible()
})
test('原型活动入口保留真实邀请边界，不接受短码或管理链接',async({page})=>{
 await page.route('**/api/v1/events',r=>r.fulfill({json:{data:[]}}));await page.goto(base)
 const input=page.getByLabel('小队邀请链接'),button=page.getByRole('button',{name:'进入',exact:true})
 await expect(button).toBeDisabled();await input.fill('K7Q2M9');await button.click();await expect(page.getByRole('alert')).toContainText('完整邀请链接');await expect(page).toHaveURL(base+'/')
 await input.fill(`${base}/groups/test#manager=${'a'.repeat(64)}`);await button.click();await expect(page.getByRole('alert')).toContainText('管理或个人恢复链接不能用于加入');await expect(page).toHaveURL(base+'/')
 for(const width of [375,390,430]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
})
test('个人缓冲步长、严格回导、云端删除与完整本机清理',async({browser})=>{
 test.setTimeout(90000);const pack=await publishFixture(browser,'personal-tools',base),context=await browser.newContext({viewport:{width:390,height:900}}),page=await context.newPage();await enter(page,pack,base)
 await page.locator('.sched-row').filter({hasText:'13:07'}).click();await page.getByRole('button',{name:'加入计划',exact:true}).click();await tab(page,'我的')
 await page.getByRole('button',{name:/^时间设置/}).click();let d=page.getByRole('dialog',{name:'时间设置'});await d.getByLabel('个人缓冲（分钟）').fill('5');await d.getByLabel('快捷步长').selectOption('5');await d.getByRole('button',{name:'保存设置',exact:true}).click();await tab(page,'计划');await save(page);await page.reload();await tab(page,'我的');await page.getByRole('button',{name:/^时间设置/}).click();d=page.getByRole('dialog');await expect(d.getByLabel('个人缓冲（分钟）')).toHaveValue('5');await expect(d.getByLabel('快捷步长')).toHaveValue('5');await close(page);await tab(page,'计划');await page.getByRole('button',{name:'日程',exact:true}).click();await page.getByRole('button',{name:/本日在场时间/}).click();d=page.getByRole('dialog');await expect(d.getByLabel('开始时间 1',{exact:true})).toHaveValue('09:00');await expect(d.getByRole('button',{name:'5 分',exact:true})).toHaveAttribute('aria-pressed','true');await d.getByLabel('开始时间 1',{exact:true}).fill('13:07');await d.getByLabel('结束时间 1',{exact:true}).fill('13:52');await d.getByRole('button',{name:'保存',exact:true}).click();await tab(page,'我的');await page.getByRole('button',{name:/^时间设置/}).click();d=page.getByRole('dialog');await d.getByLabel('快捷步长').selectOption('30');await d.getByRole('button',{name:'保存设置',exact:true}).click();await tab(page,'计划');await save(page);await tab(page,'我的')
 for(const width of [375,390,430])for(const scheme of ['light','dark'] as const){await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:scheme});await page.screenshot({animations:'disabled',path:`${evidence}/me-${width}-${scheme}.png`});await page.getByRole('button',{name:/^时间设置/}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect.poll(()=>page.getByRole('dialog').evaluate(e=>Math.round(e.getBoundingClientRect().bottom))).toBe(900);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({animations:'disabled',path:`${evidence}/settings-${width}-${scheme}.png`});await close(page)}
 await page.getByRole('button',{name:'恢复与导出'}).click();const backup=JSON.parse(await download(page,'导出个人计划'));expect(backup.plan.response.busy[0]).toMatchObject({start:'13:07',end:'13:52'});expect(backup.plan.response.bufferMinutes).toBe(5);expect(backup.plan.response.presence[0].intervals[0]).toEqual({start:'13:07',end:'13:52'});expect(backup.personId).toBeTruthy();expect(JSON.stringify(backup)).not.toMatch(/token|Bearer/)
 await page.getByRole('button',{name:'导入个人计划',exact:true}).click();d=page.getByRole('dialog');await d.getByLabel('粘贴个人计划 JSON').fill(JSON.stringify({...backup,eventId:'other-event'}));await d.getByRole('button',{name:'预览导入',exact:true}).click();await expect(d.getByRole('alert')).toContainText('当前活动')
 await d.getByLabel('粘贴个人计划 JSON').fill(JSON.stringify({...backup,personId:'other-person'}));await d.getByRole('button',{name:'预览导入',exact:true}).click();await expect(d.getByRole('alert')).toContainText('当前身份')
 await d.getByLabel('粘贴个人计划 JSON').fill(JSON.stringify(backup));await d.getByRole('button',{name:'预览导入',exact:true}).click();await expect(d).toContainText('1 条安排');await d.getByRole('button',{name:'替换本机草稿',exact:true}).click();await tab(page,'计划');await expect(page.locator('p[role=status]')).toContainText('未保存');await save(page)
 const identity=await page.evaluate(async(eventId)=>new Promise<any>((resolve,reject)=>{const r=indexedDB.open('coukong-online-v1',1);r.onsuccess=()=>{const q=r.result.transaction('records').objectStore('records').get('activity-cap:'+eventId);q.onsuccess=()=>{resolve(q.result);r.result.close()};q.onerror=()=>reject(q.error)}}),pack.event.id)
 await page.evaluate(async({eventId,personId})=>new Promise<void>(resolve=>{const r=indexedDB.open('coukong-online-v1',1);r.onsuccess=()=>{const t=r.result.transaction('records','readwrite'),s=t.objectStore('records');for(const key of [`personal-busy-editor:${eventId}:${personId}:2026-10-03`,`activity-submit:${eventId}:${personId}`,`activity-prepared:v1:${encodeURIComponent(eventId)}:public`,`activity-create-group:${eventId}`,`activity-owner:${eventId}`,'activity-cap:other-event'])s.put({fixture:true},key);t.oncomplete=()=>{r.result.close();resolve()}}}),{eventId:pack.event.id,personId:identity.personId})
 await tab(page,'我的');await page.getByRole('button',{name:'恢复与导出'}).click();page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'删除云端个人记录',exact:true}).click();expect((await page.request.get(`${API_BASE}/api/v1/events/${pack.event.id}/personal/${identity.personId}`,{headers:{Authorization:'Bearer '+identity.token}})).status()).toBe(200)
 page.once('dialog',d=>d.accept());const deleted=page.waitForResponse(r=>r.request().method()==='DELETE'&&r.url().includes('/personal/'));await page.getByRole('button',{name:'删除云端个人记录',exact:true}).click();expect((await deleted).status()).toBe(200);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page).toHaveURL(new RegExp('/events/'+pack.event.id));expect((await page.request.get(`${API_BASE}/api/v1/events/${pack.event.id}/personal/${identity.personId}`,{headers:{Authorization:'Bearer '+identity.token}})).status()).toBe(401)
 const keys=await page.evaluate(async()=>new Promise<string[]>(resolve=>{const r=indexedDB.open('coukong-online-v1',1);r.onsuccess=()=>{const q=r.result.transaction('records').objectStore('records').getAllKeys();q.onsuccess=()=>{resolve(q.result.map(String));r.result.close()}}}));expect(keys).not.toContain('activity-cap:'+pack.event.id);expect(keys).not.toContain('activity-personal:'+pack.event.id);expect(keys).not.toContain(`activity-submit:${pack.event.id}:${identity.personId}`);expect(keys).not.toContain(`personal-busy-editor:${pack.event.id}:${identity.personId}:2026-10-03`);expect(keys).toContain(`activity-owner:${pack.event.id}`);expect(keys).toContain(`activity-create-group:${pack.event.id}`);expect(keys).toContain(`activity-prepared:v1:${encodeURIComponent(pack.event.id)}:public`);expect(keys).toContain('activity-cap:other-event');await context.close()
})

test('响应丢失后的个人删除保持同一操作重试；本机移除保留云端及其他活动',async({browser})=>{
 test.setTimeout(90000);const pack=await publishFixture(browser,'personal-delete-retry',base),context=await browser.newContext(),page=await context.newPage();await enter(page,pack,base);await page.locator('.sched-row').filter({hasText:'13:07'}).click();await page.getByRole('button',{name:'加入计划',exact:true}).click();await tab(page,'计划');await save(page);await tab(page,'我的');await page.getByRole('button',{name:'恢复与导出'}).click();const recovery=await download(page,'保存个人恢复链接');const operations:unknown[]=[];let first=true
 await page.route('**/api/v1/events/*/personal/*',async route=>{if(route.request().method()!=='DELETE')return route.continue();operations.push(route.request().postDataJSON());const response=await route.fetch();if(first){first=false;return route.fulfill({status:503,json:{error:{code:'SERVICE_UNAVAILABLE',message:'隔离测试：响应丢失'}}})}await route.fulfill({response})})
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'删除云端个人记录',exact:true}).click();await expect(page.getByRole('alert')).toContainText('响应丢失');await expect(page.getByRole('dialog')).toBeVisible();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'删除云端个人记录',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page).toHaveURL(new RegExp('/events/'+pack.event.id));const oldURL=new URL(recovery),oldId=oldURL.hash.match(/personId=([^&]+)/)?.[1],oldToken=oldURL.hash.match(/personal=([^&]+)/)?.[1];expect((await page.request.get(`${API_BASE}/api/v1/events/${pack.event.id}/personal/${oldId}`,{headers:{Authorization:'Bearer '+oldToken}})).status()).toBe(401);expect(operations).toHaveLength(2);expect(operations[1]).toEqual(operations[0]);await page.unroute('**/api/v1/events/*/personal/*')
 await enter(page,pack,base);await tab(page,'探索');await page.locator('.sched-row').filter({hasText:'13:07'}).click();await page.getByRole('button',{name:'加入计划',exact:true}).click();await tab(page,'计划');await save(page);await tab(page,'我的');await page.getByRole('button',{name:'恢复与导出'}).click();const newRecovery=await download(page,'保存个人恢复链接');expect(newRecovery).not.toBe(recovery);await close(page)
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'移除此设备资料',exact:true}).click();await expect(page.getByRole('heading',{name:'选择活动',exact:true})).toBeVisible();await page.goto(newRecovery);await tab(page,'计划');await page.getByRole('button',{name:'日程',exact:true}).click();await expect(page.locator('.sched-row').filter({hasText:'13:07'})).toBeVisible();await context.close()
})
