import {expect,type Page,type Locator} from '@playwright/test'
import {readFileSync} from 'node:fs'
export async function reveal(locator:Locator){await locator.waitFor({state:'attached'});const sections=locator.locator("xpath=ancestor::*[self::details or contains(concat(' ',normalize-space(@class),' '),' disclosure ')]");for(let i=0;i<await sections.count();i++){const section=sections.nth(i);if(await section.evaluate(e=>e.tagName==='DETAILS')){if(await section.getAttribute('open')===null)await section.locator(':scope > summary').click()}else{const toggle=section.locator(':scope > button[aria-expanded]');if(await toggle.getAttribute('aria-expanded')==='false')await toggle.click()}}return locator}
export async function field(page:Page,name:string){return reveal(page.getByLabel(name).first())}
export async function action(page:Page,name:string){return reveal(page.getByRole('button',{name,exact:true,includeHidden:true}).first())}
export async function closeSheet(page:Page){const d=page.getByRole('dialog');if(await d.count()){await d.getByRole('button',{name:'关闭',exact:true}).click();await expect(d).toHaveCount(0)}}
export async function tab(page:Page,name:'日程'|'凑空'|'成员'){await closeSheet(page);await page.locator('.tabbar').getByRole('button',{name,exact:true}).click()}
export async function manager(page:Page){await tab(page,'成员');await page.getByRole('button',{name:'管理小队',exact:true}).click();await expect(page.getByRole('dialog',{name:'管理小队'})).toBeVisible()}
export async function personal(page:Page){await tab(page,'成员');await page.getByRole('button',{name:'我的入口与备份',exact:true}).click()}
export async function create(page:Page,title:string,base=process.env.TONGYE_E2E_BASE_URL||'http://localhost:5173',start='13:00',end='20:00'){await page.goto(base+'/create');await page.getByLabel('小队标题').fill(title);await page.getByLabel('开始时间 1',{exact:true}).fill(start);await page.getByLabel('结束时间 1',{exact:true}).fill(end);await page.getByLabel('站点创建码').fill('test-create');await page.getByRole('button',{name:'确认创建',exact:true}).click();await expect(page.locator('.tabbar')).toBeVisible();await manager(page);await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.getByRole('button',{name:'复制链接',exact:true}).click();const link=await page.evaluate(()=>navigator.clipboard.readText());await closeSheet(page);return link}
export async function join(page:Page,link:string,name:string){await page.goto(link);await page.getByLabel('怎么称呼').fill(name);await page.getByRole('button',{name:'加入小队',exact:true}).click();await expect(page.getByRole('button',{name:'日程设置',exact:true})).toBeVisible()}
export async function presence(page:Page,start:string,end:string){await tab(page,'日程');await page.getByRole('button',{name:/本日在场时间/}).click();const d=page.getByRole('dialog',{name:/在场时间/});await d.getByLabel('开始时间 1',{exact:true}).fill(start);await d.getByLabel('结束时间 1',{exact:true}).fill(end);await d.getByRole('button',{name:'保存',exact:true}).click();await expect(d).toHaveCount(0)}
export async function settings(page:Page,values:{name?:string;buffer?:number;step?:string}){await tab(page,'日程');await page.getByRole('button',{name:'日程设置',exact:true}).click();const d=page.getByRole('dialog',{name:'日程设置'});if(values.name!==undefined)await d.getByLabel('怎么称呼').fill(values.name);if(values.buffer!==undefined)await d.getByLabel('缓冲（分钟）').fill(String(values.buffer));if(values.step)await d.getByLabel('选择步长').selectOption(values.step);await d.getByRole('button',{name:'完成',exact:true}).click();await expect(d).toHaveCount(0)}
export async function busy(page:Page,title:string,start:string,end:string,note=''){await tab(page,'日程');await page.getByRole('button',{name:'手动添加',exact:true}).click();const d=page.getByRole('dialog',{name:'安排',exact:true});if(await d.getByRole('button',{name:'自定义',exact:true}).count())await d.getByRole('button',{name:'自定义',exact:true}).click();await d.getByLabel('活动名').fill(title);await d.getByLabel('开始时间',{exact:true}).fill(start);await d.getByLabel('结束时间',{exact:true}).fill(end);await d.getByLabel('私密备注').fill(note);await d.getByRole('button',{name:'保存',exact:true}).click();await expect(d).toHaveCount(0)}
export async function submit(page:Page,status=200){const response=page.waitForResponse(r=>r.request().method()==='PUT'&&r.url().endsWith('/response'));await page.getByRole('button',{name:'提交',exact:true}).click();expect((await response).status()).toBe(status);await expect(page.getByRole('button',{name:'提交',exact:true})).toBeEnabled();if(status===200)await expect(page.getByRole('status').filter({hasText:'已提交'})).toBeVisible()}
export async function download(page:Page,name:string){const pending=page.waitForEvent('download');await (await action(page,name)).click();return readFileSync((await (await pending).path())!,'utf8')}
export async function importEvent(page:Page,pack:unknown){await manager(page);await (await field(page,'或粘贴 JSON')).fill(JSON.stringify(pack));await page.getByRole('button',{name:'预览',exact:true}).click();await page.getByRole('button',{name:'确认导入',exact:true}).click();await expect(page.getByRole('button',{name:'确认导入',exact:true})).toHaveCount(0);await closeSheet(page)}
export async function review(page:Page){await page.getByRole('button',{name:'核对安排',exact:true}).click();page.once('dialog',d=>d.accept());await page.getByRole('dialog',{name:'核对安排'}).getByRole('button',{name:'已核对，继续填写'}).click();await expect(page.getByRole('dialog')).toHaveCount(0)}

export async function previewAdminSave(page:Page){const status=await page.getByRole('dialog').getByLabel('活动状态').inputValue();await page.getByRole('dialog').getByRole('button',{name:status==='draft'?'保存草稿':status==='published'?'发布':'预览保存',exact:true}).click()}

export async function customArrangement(page:Page){await page.getByRole('button',{name:'加入计划',exact:true}).click();await page.getByRole('dialog',{name:'加入计划'}).getByRole('button',{name:'添加自定义安排',exact:true}).click();await expect(page.getByRole('dialog',{name:'个人安排'})).toBeVisible()}
