import {test,expect,type Page} from '@playwright/test'
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs'
import {publishFixture,enter,tab,close,save} from './activity-fixture'
const directory='/tmp/tongye-visual-comparison-390'
// Seven page categories, with separate map and place-detail images (eight PNGs).
// Fixed image fixture; actual isolated local Worker/D1 activity and personal writes.
test('390×900七页同尺寸真实视觉对照',async({browser})=>{
 test.setTimeout(90000);mkdirSync(directory,{recursive:true});const pack=await publishFixture(browser,'visual-390');const context=await browser.newContext({viewport:{width:390,height:900},colorScheme:'light'}),page=await context.newPage();const manifest:{page:string;file:string;width:number;height:number}[]=[];
 async function shot(name:string,p:Page=page){expect(p.viewportSize()).toEqual({width:390,height:900});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const file=`${directory}/${name}.png`;await p.screenshot({path:file,animations:'disabled'});const png=readFileSync(file);expect(png.subarray(0,8).toString('hex')).toBe('89504e470d0a1a0a');const width=png.readUInt32BE(16),height=png.readUInt32BE(20);expect({width,height}).toEqual({width:390,height:900});manifest.push({page:name,file,width,height})}
 await page.goto('/');await expect(page.getByRole('button',{name:new RegExp(pack.event.title)})).toBeVisible();await shot('01-activity-list');await enter(page,pack);await page.getByRole('button',{name:'地图',exact:true}).click();await expect(page.locator('svg image')).toHaveAttribute('href',/^blob:/);await shot('02-map');if((page.viewportSize()?.width||0)<900)await page.getByRole('button',{name:'列表',exact:true}).click();await page.locator('.sched-row').filter({hasText:'示例地点 A'}).click();await expect(page.getByRole('dialog')).toContainText('测试标签');await expect.poll(()=>page.getByRole('dialog').evaluate(e=>Math.round(e.getBoundingClientRect().bottom))).toBe(900);await shot('03-place-detail');await close(page);
 await page.locator('.sched-row').filter({hasText:'13:07'}).click();await page.getByRole('button',{name:'加入计划',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await tab(page,'计划');await page.getByRole('button',{name:'日程',exact:true}).click();await expect(page.getByRole('button',{name:'日程',exact:true})).toHaveClass('on');await expect(page.locator('.sched-row')).toContainText('13:07');await expect(page.locator('.sched-row')).toContainText('13:52');await save(page);await shot('04-minute-plan');await tab(page,'同行');await expect(page.locator('.figma-companions-entry')).toBeVisible();await expect(page.getByRole('button',{name:'创建',exact:true})).toBeVisible();await expect(page.getByLabel('小队邀请链接')).toBeVisible();await shot('05-companions');await tab(page,'我的');await expect(page.getByRole('button',{name:'为现场准备离线数据'})).toBeVisible();await shot('06-me');await page.getByLabel('外观',{exact:true}).selectOption('dark');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.getByLabel('外观',{exact:true}).selectOption('light');await expect(page.locator('html')).toHaveAttribute('data-theme','light');
 const admin=await browser.newContext({viewport:{width:390,height:900},colorScheme:'light'}),adminPage=await admin.newPage();await adminPage.goto('/admin');await adminPage.getByLabel('管理员密码').fill('a'.repeat(64));await adminPage.getByRole('button',{name:'进入管理'}).click();await expect(adminPage.getByRole('button',{name:new RegExp(pack.event.title)})).toBeVisible();await expect(adminPage.getByLabel('管理员密码')).toHaveCount(0);await shot('07-administrator',adminPage);await page.goto('/help/index.html');await expect(page.locator('body')).toContainText('邀请');await shot('08-help');writeFileSync(`${directory}/dimensions.json`,JSON.stringify({viewport:{width:390,height:900},imageSource:'本地固定虚构PNG，不是云上传或真实现场地图',images:manifest},null,2));console.log(JSON.stringify({evidence:directory,images:manifest.map(v=>({page:v.page,width:v.width,height:v.height}))}));await admin.close();await context.close();
})

for(const scheme of ['light','dark'] as const)test(`最近小队${scheme}仅有记录时直接显示并可点击`,async({browser})=>{
 const {create}=await import('./ui-helpers');const context=await browser.newContext({viewport:{width:390,height:900},colorScheme:scheme}),page=await context.newPage();await page.goto('/');await expect(page.getByText('最近小队',{exact:true})).toHaveCount(0);await expect(page.locator('summary')).toHaveCount(0);await page.screenshot({path:`${directory}/recent-empty-${scheme}.png`,animations:'disabled'});const title=`视觉小队示例-${scheme}`;await create(page,title);await page.goto('/');await expect(page.getByText('最近小队',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:title,exact:true})).toBeVisible();await expect(page.locator('summary')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${directory}/recent-list-${scheme}.png`,animations:'disabled'});await page.getByRole('button',{name:title,exact:true}).click();await expect(page).toHaveURL(/\/groups\//);await expect(page.locator('.page-sub').filter({hasText:title})).toBeVisible();await context.close();
})
