import { handleCreationInvites } from './creation-invites'
import { handleActivity, loadReadableActivity, eventAccessSQL, eventAccessArgs } from './activity'
import { handleMedia, verifyVercelOIDC, type VercelOIDCConfig } from './media'
import { parseEventPackage, parseStrictJSON, validateEventPackage, validateResponse } from '../../shared/event-validation'
import { personalAvailability } from '../../shared/availability'
import { ACTIVITY_LIMITS } from '../../shared/activity-contract'
import { GROUP_LIMITS } from '../../shared/group-contract'
import type { EventPackage } from '../../shared/types'
interface Env extends VercelOIDCConfig { DB:D1Database; ALLOWED_ORIGINS:string; CREATION_MODE:string; CREATION_CODE?:string; ADMIN_ROOT_SECRET?:string; BUILD_VERSION:string }
type Row=Record<string,any>
class ApiError extends Error { constructor(public code:string, message:string, public status=400){super(message)} }
const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),x=>x.toString(16).padStart(2,'0')).join('')
const token=(s:unknown)=>{if(typeof s!=='string'||! /^[a-f0-9]{64}$/.test(s))throw new ApiError('INVALID_CAPABILITY','需要有效的高熵凭据',401);return s}
const op=(s:unknown)=>{if(typeof s!=='string'||! /^[\w-]{16,100}$/.test(s))throw new ApiError('INVALID_REQUEST','operationId 无效');return s}
const safeMember=(m:Row,g:Row)=>({id:m.id,name:m.name,status:m.submitted_at?(m.schedule_revision===g.schedule_revision?'confirmed':'needs_review'):'unsubmitted',revision:m.revision,confirmedScheduleRevision:m.schedule_revision,updatedAt:m.updated_at,submittedAt:m.submitted_at})
const safeGroup=(g:Row)=>({id:g.id,title:g.title,status:g.status,revision:g.revision,scheduleRevision:g.schedule_revision,eventPackage:JSON.parse(g.event_json),createdAt:g.created_at,updatedAt:g.updated_at,...(g.source_event_id?{sourceEventId:g.source_event_id,sourceEventRevision:g.source_event_revision,sourceScheduleRevision:g.source_schedule_revision,sourceSpatialRevision:g.source_spatial_revision}:{})})
function schedule(p:EventPackage){const e=p.event;return JSON.stringify([e.timezone,e.startDate,e.endDate,e.days,e.defaultBufferMinutes,e.defaultMinSlotMinutes,e.activities.map(a=>[a.id,a.sessions])])}
function preview(g:Row,p:EventPackage){const old=JSON.parse(g.event_json) as EventPackage;const oldS=old.event.activities.flatMap(a=>a.sessions);const newS=p.event.activities.flatMap(a=>a.sessions);return {eventPackage:p,changed:JSON.stringify(old)!==JSON.stringify(p),scheduleChanged:schedule(old)!==schedule(p),warnings:p.meta?.sourceNote?[p.meta.sourceNote]:[],added:newS.filter(s=>!oldS.some(x=>x.id===s.id)).map(s=>s.id),removed:oldS.filter(s=>!newS.some(x=>x.id===s.id)).map(s=>s.id),modified:newS.filter(s=>oldS.some(x=>x.id===s.id&&JSON.stringify(x)!==JSON.stringify(s))).map(s=>s.id),expectedRevision:g.revision}}
async function handle(req:Request,env:Env){
 const url=new URL(req.url), path=url.pathname.replace(/^\/api\/v1/,'');const method=req.method, now=new Date().toISOString();
 const run=(sql:string,...args:any[])=>env.DB.prepare(sql).bind(...args).run();const first=(sql:string,...args:any[])=>env.DB.prepare(sql).bind(...args).first<Row>();
 const bearer=req.headers.get('Authorization')?.replace(/^Bearer /,'')||'';const authHash=bearer?await hash(bearer):'';
 // A raw package's JSON-string envelope may encode each character as six-byte \uXXXX.
 // Expand only actual package-writing routes; identity and personal bodies keep 2 MiB.
 const carriesPackage=(method==='POST'&&(['/admin/events','/admin/templates','/groups','/private-events'].includes(path)||/^\/groups\/[^/]+\/event-import\/(preview|commit)$/.test(path)))||(method==='PATCH'&&/^\/events\/[^/]+$/.test(path))
 const body=async()=>{const max=carriesPackage?6*ACTIVITY_LIMITS.packageBytes+64*1024:2*1024*1024;if(Number(req.headers.get('Content-Length'))>max)throw new ApiError('LIMIT_EXCEEDED','请求过大',413);let text='',bytes=0;const reader=req.body?.getReader(),decoder=new TextDecoder('utf-8',{fatal:true,ignoreBOM:false});if(reader){try{while(true){const chunk=await reader.read();if(chunk.done)break;bytes+=chunk.value.byteLength;if(bytes>max){await reader.cancel();throw new ApiError('LIMIT_EXCEEDED','请求过大',413)}text+=decoder.decode(chunk.value,{stream:true})}text+=decoder.decode()}catch(e){if(e instanceof ApiError)throw e;throw new ApiError('INVALID_REQUEST','需要有效 UTF-8 JSON')}}try{const parsed=parseStrictJSON(text,max);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('object required');const b=parsed as Row;if(('expectedRevision' in b)&&(!Number.isInteger(b.expectedRevision)||b.expectedRevision<0))throw new ApiError('INVALID_REQUEST','expectedRevision 必须为非负整数');if(('scheduleRevision' in b)&&(!Number.isInteger(b.scheduleRevision)||b.scheduleRevision<0))throw new ApiError('INVALID_REQUEST','scheduleRevision 必须为非负整数');if((method==='PUT'||(method==='PATCH'&&!path.startsWith('/admin/'))||path.endsWith('/event-import/commit')||path.endsWith('/source-refresh')||path.endsWith('/invite/rotate')||(method==='DELETE'&&/^\/groups\/[^/]+$/.test(path)))&&!Number.isInteger(b.expectedRevision))throw new ApiError('INVALID_REQUEST','需要 expectedRevision');if(method==='PUT'&&!Number.isInteger(b.scheduleRevision))throw new ApiError('INVALID_REQUEST','需要 scheduleRevision');return b}catch(e){if(e instanceof ApiError)throw e;throw new ApiError('INVALID_REQUEST','JSON 无效')}};
 const limited=async(key:string,max:number)=>{const window=Math.floor(Date.now()/60000);await run('INSERT INTO rate_limits(key,window,count) VALUES(?,?,1) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN window=excluded.window THEN count+1 ELSE 1 END,window=excluded.window',key,window);const r=await first('SELECT count FROM rate_limits WHERE key=?',key);if(r!.count>max)throw new ApiError('LIMIT_EXCEEDED','请求过于频繁，请稍后重试',429)};
 const admin=async()=>{const s=await first('SELECT hash FROM admin_sessions WHERE hash=? AND expires_at>?',authHash,Date.now());if(!s)throw new ApiError('INVALID_CAPABILITY','管理员会话无效',401)};
 if(path==='/health')return {version:env.BUILD_VERSION,alive:true};
 if(path==='/ready'){await first('SELECT id FROM groups LIMIT 1');await first('SELECT id FROM events LIMIT 1');await first('SELECT id FROM creation_invites LIMIT 1');return {ready:true,version:env.BUILD_VERSION}}
 if(path==='/admin/session'){
  if(method==='DELETE'){await run('DELETE FROM admin_sessions WHERE hash=?',authHash);return {revoked:true}}
  await limited('admin:'+ (req.headers.get('CF-Connecting-IP')||'local'),10);const b=await body();if(!env.ADMIN_ROOT_SECRET||await hash(String(b.rootSecret??b.rootToken))!==await hash(env.ADMIN_ROOT_SECRET))throw new ApiError('INVALID_CAPABILITY','管理员凭据无效',401);const session=token(b.sessionToken);await run('INSERT OR REPLACE INTO admin_sessions VALUES(?,?)',await hash(session),Date.now()+3600000);return {expiresAt:new Date(Date.now()+3600000).toISOString()}
 }
 if(path.startsWith('/admin/creation-invites')){const grants=await handleCreationInvites({req,DB:env.DB,path,method,authHash,now,body,hash,token,op,admin,limited,fail:(code,message,status=400)=>{throw new ApiError(code,message,status)}},await Promise.all([env.CREATION_CODE,env.ADMIN_ROOT_SECRET].filter((s):s is string=>!!s).map(hash)));if(grants?.handled)return grants.data;}
 const media=await handleMedia({req,DB:env.DB,path,method,authHash,now,body,hash,token,op,admin,limited,fail:(code,message,status=400)=>{throw new ApiError(code,message,status)},verifyNode:async()=>{try{await verifyVercelOIDC(req,env)}catch{throw new ApiError('FORBIDDEN','媒体运行时证明无效',403)}}});if(media.handled)return media.data;
 const activity=await handleActivity({req,DB:env.DB,path,method,authHash,now,body,hash,token,op,admin,creation:async(code)=>{if(env.CREATION_MODE!=='invite'||!env.CREATION_CODE||await hash(String(code))!==await hash(env.CREATION_CODE))throw new ApiError('FORBIDDEN','创建保护未通过',403)},limited,fail:(code,message,status=400)=>{throw new ApiError(code,message,status)}});if(activity.handled)return activity.data;
 if(path==='/templates'&&method==='GET'){const rows=await env.DB.prepare('SELECT t.* FROM templates t WHERE t.published=1 AND NOT EXISTS (SELECT 1 FROM templates newer WHERE newer.id=t.id AND newer.revision>t.revision) ORDER BY t.updated_at DESC LIMIT 50').all<Row>();return rows.results.map(t=>({id:t.id,revision:t.revision,published:true,eventPackage:JSON.parse(t.event_json),updatedAt:t.updated_at}))}
 if(path.startsWith('/admin/')){
  await admin();if(path==='/admin/audit'&&method==='GET')return (await env.DB.prepare('SELECT action,group_id AS groupId,resource_id AS resourceId,created_at AS createdAt FROM audit ORDER BY id DESC LIMIT 100').all()).results;if(path==='/admin/groups'&&method==='GET')return (await env.DB.prepare('SELECT id,title,status,updated_at FROM groups LIMIT 100').all()).results;
  const gm=path.match(/^\/admin\/groups\/([^/]+)$/);if(gm&&method==='PATCH'){const b=await body();if(!['closed','archived'].includes(b.status))throw new ApiError('INVALID_REQUEST','状态无效');await run('UPDATE groups SET status=?,revision=revision+1,updated_at=? WHERE id=?',b.status,now,gm[1]);return {updated:true}}
  if(path==='/admin/templates'&&method==='GET')return (await env.DB.prepare('SELECT t.* FROM templates t WHERE NOT EXISTS (SELECT 1 FROM templates newer WHERE newer.id=t.id AND newer.revision>t.revision) ORDER BY t.updated_at DESC LIMIT 100').all<Row>()).results.map(t=>({id:t.id,revision:t.revision,published:!!t.published,eventPackage:JSON.parse(t.event_json),updatedAt:t.updated_at}));
  if(path==='/admin/templates'&&method==='POST'){const b=await body();const p=typeof b.raw==='string'?parseEventPackage(b.raw):validateEventPackage(b.eventPackage);const id=p.event.id,operation=op(b.operationId),digest=await hash(JSON.stringify(b)),scope=authHash+':template:'+id;const remembered=await first('SELECT * FROM operations WHERE scope=? AND op=?',scope,operation);if(remembered){if(remembered.digest!==digest)throw new ApiError('VERSION_CONFLICT','操作内容变化',409);return JSON.parse(remembered.result_json)}const latest=await first('SELECT MAX(revision) AS revision FROM templates WHERE id=?',id);const revision=(latest?.revision||0)+1;if((b.expectedRevision??0)!==revision-1)throw new ApiError('VERSION_CONFLICT','模板版本已变化',409);const result={id,revision,published:!!b.published,eventPackage:p,updatedAt:now};const batch=await env.DB.batch([env.DB.prepare('INSERT INTO templates(id,revision,published,event_json,updated_at,operation_id,operation_digest) SELECT ?,?,?,?,?,?,? WHERE COALESCE((SELECT MAX(revision) FROM templates WHERE id=?),0)=? AND EXISTS(SELECT 1 FROM admin_sessions WHERE hash=? AND expires_at>?) ON CONFLICT(id,revision) DO NOTHING').bind(id,revision,b.published?1:0,JSON.stringify(p),now,operation,digest,id,b.expectedRevision??0,authHash,Date.now()),env.DB.prepare('INSERT INTO operations(scope,op,digest,result_json) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM templates WHERE id=? AND revision=? AND operation_id=? AND operation_digest=?) ON CONFLICT(scope,op) DO NOTHING').bind(scope,operation,digest,JSON.stringify(result),id,revision,operation,digest)]);if(!batch[0].meta.changes)throw new ApiError('VERSION_CONFLICT','模板版本或管理员会话已变化',409);return result}
  const tm=path.match(/^\/admin\/templates\/([^/]+)\/(\d+)$/);if(tm&&method==='PATCH'){const b=await body();await run('UPDATE templates SET published=? WHERE id=? AND revision=?',b.published?1:0,tm[1],+tm[2]);return {updated:true}}
 }
 if(path==='/groups'&&method==='POST'){
  await limited('create:'+(req.headers.get('CF-Connecting-IP')||'local'),20);
  const b=await body(), creationHash=await hash(String(b.creationCode??''));
  const sourceId=b.sourceEventId??b.eventId;
  const sourceHash=b.sourceEventToken?await hash(token(b.sourceEventToken)):authHash;
  const source=sourceId?await loadReadableActivity(env.DB,String(sourceId),sourceHash):null;
  const publicCreation=b.creationCode===undefined&&source?.visibility==='public';
  const siteCode=env.CREATION_MODE==='invite'&&!!env.CREATION_CODE&&creationHash===await hash(env.CREATION_CODE);
  const grant=siteCode||publicCreation?null:await first('SELECT * FROM creation_invites WHERE token_hash=?',creationHash);
  if(!publicCreation&&!siteCode&&(env.CREATION_MODE!=='invite'||!grant||grant.event_id!==sourceId))throw new ApiError('FORBIDDEN','建队码无效或不适用于此活动',403);
  const manager=await hash(token(b.managerToken)),invite=await hash(token(b.inviteToken)),operation=op(b.operationId),digest=await hash(JSON.stringify(b));
  if(manager===invite||(grant&&(manager===creationHash||invite===creationHash)))throw new ApiError('INVALID_CAPABILITY','管理、邀请与建队码必须分开',401);
  const priorGroup=await first('SELECT * FROM groups WHERE manager_hash=?',manager);
  if(priorGroup){
   if(priorGroup.create_op!==operation||priorGroup.create_digest!==digest)throw new ApiError('VERSION_CONFLICT','凭据或操作已使用',409);
   if(grant){const consumed=await first('SELECT used_group_id FROM creation_invites WHERE id=? AND token_hash=?',grant.id,creationHash);if(consumed?.used_group_id!==priorGroup.id)throw new ApiError('FORBIDDEN','建队码没有创建此小队',403);}
   return safeGroup(priorGroup);
  }
  if(grant?.used_group_id)throw new ApiError('CREATION_INVITE_USED','该建队码已被使用。',403);
  if(grant?.revoked_at)throw new ApiError('CREATION_INVITE_REVOKED','该建队码已被撤销。',403);
  if(grant&&Date.parse(grant.expires_at)<=Date.now())throw new ApiError('CREATION_INVITE_EXPIRED','该建队码已过期。',403);
  if(sourceId&&(!source||source.status!=='published'))throw new ApiError('EVENT_UNAVAILABLE','活动未发布、取消或已归档',409);
  if(grant&&source?.visibility!=='public')throw new ApiError('FORBIDDEN','建队码仅适用于绑定的公开活动',403);
  if(source&&b.sourceEventRevision!==undefined&&b.sourceEventRevision!==source.revision)throw new ApiError('VERSION_CONFLICT','活动版本已变化',409);
  const p=source?source.eventPackage:validateEventPackage(b.eventPackage),id=crypto.randomUUID();
  if(b.title!==undefined&&(typeof b.title!=='string'||!b.title.trim()||b.title.trim().length>100))throw new ApiError('INVALID_REQUEST','小队标题须为1–100字');
  const groupTitle=typeof b.title==='string'?b.title.trim():p.event.title;
  const sourceGuard="(? IS NULL OR EXISTS(SELECT 1 FROM events e JOIN event_versions v ON v.event_id=e.id AND v.revision=CASE WHEN e.visibility='private' THEN e.revision ELSE e.public_revision END WHERE e.id=? AND v.revision=? AND v.status='published' AND "+eventAccessSQL+(publicCreation?" AND e.visibility='public'":"")+"))";
  const grantGuard=grant?" AND EXISTS(SELECT 1 FROM creation_invites c WHERE c.id=? AND c.token_hash=? AND c.event_id=? AND c.used_group_id IS NULL AND c.revoked_at IS NULL AND c.expires_at>strftime('%Y-%m-%dT%H:%M:%fZ','now'))":"";
  const insert=env.DB.prepare('INSERT INTO groups(id,title,event_json,manager_hash,invite_hash,create_op,create_digest,created_at,updated_at,source_event_id,source_event_revision,source_schedule_revision,source_spatial_revision,creation_invite_id) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM groups WHERE manager_hash=?) AND '+sourceGuard+grantGuard+' ON CONFLICT(manager_hash) DO NOTHING').bind(id,groupTitle,JSON.stringify(p),manager,invite,operation,digest,now,now,source?.id??null,source?.revision??null,source?.scheduleRevision??null,source?.spatialRevision??null,grant?.id??null,manager,source?.id??null,source?.id??null,source?.revision??null,...eventAccessArgs(sourceHash),...(grant?[grant.id,creationHash,source!.id]:[]));
  const results=await env.DB.batch([insert]);
  if(!results[0].meta.changes){
   // The identical request can race its first response. Re-read under the same
   // manager capability and full request digest; operationId never grants access.
   const replay=await first('SELECT * FROM groups WHERE manager_hash=?',manager);
   const consumed=grant?await first('SELECT used_group_id FROM creation_invites WHERE id=?',grant.id):null;
   if(replay?.create_op===operation&&replay.create_digest===digest&&(!grant||consumed?.used_group_id===replay.id))return safeGroup(replay);
   if(grant){const current=await first('SELECT * FROM creation_invites WHERE id=?',grant.id);if(current?.used_group_id||current?.revoked_at||Date.parse(current?.expires_at)<=Date.now())throw new ApiError('FORBIDDEN','建队码已使用、已撤销或已过期',403);}
   throw new ApiError('VERSION_CONFLICT','活动版本或创建操作已变化',409);
  }
  return safeGroup((await first('SELECT * FROM groups WHERE id=?',id))!);
 }
 const match=path.match(/^\/groups\/([^/]+)(.*)$/);if(!match)throw new ApiError('NOT_FOUND','接口不存在',404);const groupId=match[1],tail=match[2];const g=await first('SELECT * FROM groups WHERE id=?',groupId);if(!g){if(method==='DELETE'&&tail===''){const tombstone=await first('SELECT * FROM group_tombstones WHERE id=? AND manager_hash=?',groupId,authHash);if(tombstone){if(Date.parse(tombstone.deleted_at)+GROUP_LIMITS.tombstoneTTLSeconds*1000<=Date.now())throw new ApiError('IDEMPOTENCY_EXPIRED','删除回执已过期',409);const b=await body();if(tombstone.operation_id!==op(b.operationId)||tombstone.digest!==await hash(JSON.stringify(b)))throw new ApiError('VERSION_CONFLICT','删除操作内容变化',409);return {deleted:true}}}throw new ApiError('NOT_FOUND','小队不存在',404)}
 const member=await first('SELECT * FROM members WHERE group_id=? AND token_hash=?',groupId,authHash);const role=g.manager_hash===authHash?'manager':g.invite_hash===authHash?'invite':member?'member':null;
 if(!role){await limited('invalid:'+(req.headers.get('CF-Connecting-IP')||'local'),30);throw new ApiError('INVALID_CAPABILITY','凭据无效或已撤销',401)}
 const manager=()=>{if(role!=='manager')throw new ApiError('FORBIDDEN','需要发起人权限',403)};
 const receipt=async(scope:string,operation:string,digest:string,current:Row=g)=>{
  const saved=await first('SELECT * FROM operations WHERE scope=? AND op=?',scope,operation);
  if(saved){if(saved.digest!==digest)throw new ApiError('VERSION_CONFLICT','同一操作内容发生变化',409);if(saved.expires_at<=Date.now())throw new ApiError('IDEMPOTENCY_EXPIRED','操作回执已过期，请回读当前状态并创建新操作',409);return JSON.parse(saved.result_json)}
  if(current.last_op===operation){if(current.last_digest!==digest)throw new ApiError('VERSION_CONFLICT','同一操作内容发生变化',409);throw new ApiError('IDEMPOTENCY_EXPIRED','操作回执已过期，请回读当前状态并创建新操作',409)}
  return null;
 };

 if(method==='GET'&&tail===''){const source=g.source_event_id?await loadReadableActivity(env.DB,g.source_event_id,authHash):null;return {...safeGroup(g),...(g.source_event_id?{sourceStatus:source?.status??'unavailable',sourceVisibility:source?.visibility??null,currentSourceRevision:source?.revision??null}:{})}}
 if(method==='GET'&&tail==='/event-export')return JSON.parse(g.event_json);
 if(method==='GET'&&(tail==='/members'||tail==='/availability')){const rows=(await env.DB.prepare('SELECT * FROM members WHERE group_id=? ORDER BY created_at,id').bind(groupId).all<Row>()).results;if(tail==='/members')return rows.map(m=>safeMember(m,g));return {members:rows.map(m=>({...safeMember(m,g),availability:m.schedule_revision===g.schedule_revision&&m.submitted_at?JSON.parse(m.availability_json||'[]'):[]})),scheduleRevision:g.schedule_revision,updatedAt:[g.updated_at,...rows.map(m=>m.updated_at)].sort().at(-1)}}
 if(tail==='/join'&&method==='POST'){
  if(role!=='invite')throw new ApiError('FORBIDDEN','请使用邀请入口加入',403);const b=await body(),memberHash=await hash(token(b.memberToken)),operation=op(b.operationId),digest=await hash(JSON.stringify(b));const existing=await first('SELECT * FROM members WHERE group_id=? AND token_hash=?',groupId,memberHash);if(existing){if(existing.join_op!==operation||existing.join_digest!==digest)throw new ApiError('VERSION_CONFLICT','操作已使用',409);return safeMember(existing,g)}
  if(typeof b.name!=='string'||!b.name.trim()||b.name.trim().length>50)throw new ApiError('INVALID_REQUEST','名字必须为1–50字');const id=crypto.randomUUID();await run("INSERT INTO members(id,group_id,name,token_hash,join_op,join_digest,created_at,updated_at) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM groups WHERE id=? AND status='open' AND invite_hash=?)",id,groupId,b.name.trim(),memberHash,operation,digest,now,now,groupId,authHash);const m=await first('SELECT * FROM members WHERE id=?',id);if(!m)throw new ApiError('GROUP_CLOSED','邀请失效或小队已关闭',409);return safeMember(m,g)
 }
 const mm=tail.match(/^\/members\/([^/]+)(\/response)?$/);
 if(mm){const target=mm[1];if(mm[2]){
  if(role!=='member'||member!.id!==target)throw new ApiError('FORBIDDEN','只能访问本人的私人回复',403);
  if(method==='GET')return {member:safeMember(member!,g),response:member!.response_json?JSON.parse(member!.response_json):null};
  if(method==='PUT'){await limited('write:'+authHash,60);const b=await body(),operation=op(b.operationId),digest=await hash(JSON.stringify(b));const saved=await receipt(authHash+':'+target,operation,digest,member!);if(saved)return saved;
   const response=validateResponse(b.response,JSON.parse(g.event_json).event),availability=personalAvailability(JSON.parse(g.event_json).event,response);const result={member:{...safeMember(member!,g),name:response.name,status:'confirmed',revision:b.expectedRevision+1,confirmedScheduleRevision:b.scheduleRevision,updatedAt:now,submittedAt:now},response};
   const results=await env.DB.batch([env.DB.prepare("UPDATE members SET name=?,response_json=?,availability_json=?,revision=revision+1,schedule_revision=?,last_op=?,last_digest=?,updated_at=?,submitted_at=? WHERE id=? AND group_id=? AND token_hash=? AND revision=? AND EXISTS(SELECT 1 FROM groups WHERE id=? AND status='open' AND schedule_revision=?)").bind(response.name,JSON.stringify(response),JSON.stringify(availability),b.scheduleRevision,operation,digest,now,now,target,groupId,authHash,b.expectedRevision,groupId,b.scheduleRevision),env.DB.prepare('INSERT INTO operations(scope,op,digest,result_json,group_id,member_id,created_at,expires_at) SELECT ?,?,?,?,?,?,CAST(strftime(\'%s\',\'now\') AS INTEGER)*1000,CAST(strftime(\'%s\',\'now\') AS INTEGER)*1000+'+GROUP_LIMITS.receiptTTLSeconds*1000+' WHERE EXISTS(SELECT 1 FROM members WHERE id=? AND token_hash=? AND last_op=? AND last_digest=?) ON CONFLICT(scope,op) DO NOTHING').bind(authHash+':'+target,operation,digest,JSON.stringify(result),groupId,target,target,authHash,operation,digest)]);
   if(!results[0].meta.changes)throw new ApiError('VERSION_CONFLICT','个人或活动版本已变化，请保留草稿并重新核对',409);return result
  }
 }else if(method==='DELETE'){if(role!=='manager'&&!(role==='member'&&member!.id===target))throw new ApiError('FORBIDDEN','没有移除权限',403);await run('DELETE FROM members WHERE id=? AND group_id=?',target,groupId);return {deleted:true}}}
 if(tail==='/event-import/preview'&&method==='POST'){manager();const b=await body();return preview(g,typeof b.raw==='string'?parseEventPackage(b.raw):validateEventPackage(b.eventPackage))}
 if((tail==='/event-import/commit'||tail==='/source-refresh')&&method==='POST'){manager();const b=await body();const retryOperation=op(b.operationId),retryDigest=await hash(JSON.stringify(b));const prior=await receipt(authHash+':event:'+groupId,retryOperation,retryDigest);if(prior)return prior;if(g.source_event_id&&tail!=='/source-refresh'&&(await first('SELECT visibility FROM events WHERE id=?',g.source_event_id))?.visibility!=='private')throw new ApiError('FORBIDDEN','本队使用公共活动快照，请使用更新活动资料入口',403);const source=tail==='/source-refresh'&&g.source_event_id?await loadReadableActivity(env.DB,g.source_event_id,authHash):null;if(tail==='/source-refresh'&&(!source||source.status!=='published'))throw new ApiError('EVENT_UNAVAILABLE','公共活动未发布、取消或已归档',409);if(source&&b.sourceEventRevision!==source.revision)throw new ApiError('VERSION_CONFLICT','公共活动版本已变化，请重新预览',409);const p=source?source.eventPackage:typeof b.raw==='string'?parseEventPackage(b.raw):validateEventPackage(b.eventPackage),change=preview(g,p),operation=op(b.operationId),digest=await hash(JSON.stringify(b));if(source)change.scheduleChanged=source.scheduleRevision!==g.source_schedule_revision;
  const old=JSON.parse(g.event_json) as EventPackage;if(old.event.timezone!==p.event.timezone&&(await first('SELECT id FROM members WHERE group_id=? AND submitted_at IS NOT NULL LIMIT 1',groupId)))throw new ApiError('FORBIDDEN','已有确认成员时请创建新小队以修改时区',403);
  const result={...safeGroup(g),title:source?g.title:p.event.title,eventPackage:p,revision:g.revision+1,scheduleRevision:g.schedule_revision+(change.scheduleChanged?1:0),updatedAt:now,...(source?{sourceEventId:source.id,sourceEventRevision:source.revision,sourceScheduleRevision:source.scheduleRevision,sourceSpatialRevision:source.spatialRevision}:{})};const batch=await env.DB.batch([env.DB.prepare('UPDATE groups SET title=?,event_json=?,revision=revision+?,schedule_revision=schedule_revision+?,last_op=?,last_digest=?,updated_at=?,source_event_revision=COALESCE(?,source_event_revision),source_schedule_revision=COALESCE(?,source_schedule_revision),source_spatial_revision=COALESCE(?,source_spatial_revision) WHERE id=? AND manager_hash=? AND revision=? AND (?=0 OR NOT EXISTS(SELECT 1 FROM members WHERE group_id=? AND submitted_at IS NOT NULL)) AND (? IS NULL OR EXISTS(SELECT 1 FROM events e JOIN event_versions v ON v.event_id=e.id AND v.revision=CASE WHEN e.visibility=\'private\' THEN e.revision ELSE e.public_revision END WHERE e.id=? AND v.revision=? AND v.status=\'published\'))').bind(source?g.title:p.event.title,JSON.stringify(p),1,change.scheduleChanged?1:0,operation,digest,now,source?.revision??null,source?.scheduleRevision??null,source?.spatialRevision??null,groupId,authHash,b.expectedRevision,old.event.timezone!==p.event.timezone?1:0,groupId,source?.id??null,source?.id??null,source?.revision??null),env.DB.prepare('INSERT INTO operations(scope,op,digest,result_json,group_id,created_at,expires_at) SELECT ?,?,?,?,?,CAST(strftime(\'%s\',\'now\') AS INTEGER)*1000,CAST(strftime(\'%s\',\'now\') AS INTEGER)*1000+'+GROUP_LIMITS.receiptTTLSeconds*1000+' WHERE EXISTS(SELECT 1 FROM groups WHERE id=? AND manager_hash=? AND last_op=? AND last_digest=?) ON CONFLICT(scope,op) DO NOTHING').bind(authHash+':event:'+groupId,operation,digest,JSON.stringify(result),groupId,groupId,authHash,operation,digest)]);if(!batch[0].meta.changes)throw new ApiError('VERSION_CONFLICT','活动版本已变化',409);return result
 }
 if(tail==='/invite/rotate'&&method==='POST'){manager();const b=await body(),invite=await hash(token(b.inviteToken)),operation=op(b.operationId),digest=await hash(JSON.stringify(b));if(invite===g.manager_hash)throw new ApiError('INVALID_CAPABILITY','管理与邀请凭据必须分开',401);const scope=authHash+':rotate:'+groupId;const remembered=await receipt(scope,operation,digest);if(remembered)return remembered;const result={...safeGroup(g),revision:g.revision+1,updatedAt:now};const batch=await env.DB.batch([env.DB.prepare('UPDATE groups SET invite_hash=?,revision=revision+1,last_op=?,last_digest=?,updated_at=? WHERE id=? AND manager_hash=? AND revision=?').bind(invite,operation,digest,now,groupId,authHash,b.expectedRevision),env.DB.prepare('INSERT INTO operations(scope,op,digest,result_json,group_id,created_at,expires_at) SELECT ?,?,?,?,?,CAST(strftime(\'%s\',\'now\') AS INTEGER)*1000,CAST(strftime(\'%s\',\'now\') AS INTEGER)*1000+'+GROUP_LIMITS.receiptTTLSeconds*1000+' WHERE EXISTS(SELECT 1 FROM groups WHERE id=? AND manager_hash=? AND last_op=? AND last_digest=?) ON CONFLICT(scope,op) DO NOTHING').bind(scope,operation,digest,JSON.stringify(result),groupId,groupId,authHash,operation,digest)]);if(!batch[0].meta.changes)throw new ApiError('VERSION_CONFLICT','小队版本已变化',409);return result}
 if(tail===''&&method==='PATCH'){manager();const b=await body(),operation=op(b.operationId),digest=await hash(JSON.stringify(b)),scope=authHash+':status:'+groupId;const remembered=await receipt(scope,operation,digest);if(remembered)return remembered;if(!['open','closed','archived'].includes(b.status))throw new ApiError('INVALID_REQUEST','状态无效');const result={...safeGroup(g),status:b.status,revision:g.revision+1,updatedAt:now};const batch=await env.DB.batch([env.DB.prepare('UPDATE groups SET status=?,revision=revision+1,last_op=?,last_digest=?,updated_at=? WHERE id=? AND manager_hash=? AND revision=?').bind(b.status,operation,digest,now,groupId,authHash,b.expectedRevision),env.DB.prepare('INSERT INTO operations(scope,op,digest,result_json,group_id,created_at,expires_at) SELECT ?,?,?,?,?,CAST(strftime(\'%s\',\'now\') AS INTEGER)*1000,CAST(strftime(\'%s\',\'now\') AS INTEGER)*1000+'+GROUP_LIMITS.receiptTTLSeconds*1000+' WHERE EXISTS(SELECT 1 FROM groups WHERE id=? AND manager_hash=? AND last_op=? AND last_digest=?) ON CONFLICT(scope,op) DO NOTHING').bind(scope,operation,digest,JSON.stringify(result),groupId,groupId,authHash,operation,digest)]);if(!batch[0].meta.changes)throw new ApiError('VERSION_CONFLICT','小队版本已变化',409);return result}
 if(tail===''&&method==='DELETE'){manager();const b=await body(),operation=op(b.operationId),digest=await hash(JSON.stringify(b));if(b.confirm!==groupId)throw new ApiError('INVALID_REQUEST','请明确确认删除小队');const batch=await env.DB.batch([env.DB.prepare('DELETE FROM groups WHERE id=? AND manager_hash=? AND revision=?').bind(groupId,authHash,b.expectedRevision),env.DB.prepare('INSERT INTO group_tombstones(id,manager_hash,operation_id,digest,deleted_at) SELECT ?,?,?,?,? WHERE changes()=1').bind(groupId,authHash,operation,digest,now)]);if(!batch[0].meta.changes)throw new ApiError('VERSION_CONFLICT','小队版本已变化，请重新确认删除',409);return {deleted:true}}
 throw new ApiError('NOT_FOUND','接口不存在',404)
}
export default {async fetch(req:Request,env:Env):Promise<Response>{const origin=req.headers.get('Origin');const allowed=env.ALLOWED_ORIGINS?.split(',').map(x=>x.trim())||[];const headers:Record<string,string>={'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store','Vary':'Origin','X-Content-Type-Options':'nosniff'};if(origin&&allowed.includes(origin)){headers['Access-Control-Allow-Origin']=origin;headers['Access-Control-Allow-Headers']='Authorization, Content-Type';headers['Access-Control-Allow-Methods']='GET, POST, PUT, PATCH, DELETE, OPTIONS'}if(origin&&!allowed.includes(origin))return new Response(JSON.stringify({error:{code:'FORBIDDEN',message:'来源未获允许'}}),{status:403,headers});if(req.method==='OPTIONS')return new Response(null,{status:204,headers});try{return new Response(JSON.stringify({data:await handle(req,env)}),{headers})}catch(e:any){if(String(e?.message).includes('CREATION_INVITE_LIMIT'))e=new ApiError('LIMIT_EXCEEDED','可用建队码或历史记录已达上限',429);if(String(e?.message).includes('CREATION_INVITE_UNAVAILABLE'))e=new ApiError('FORBIDDEN','建队码已使用、已撤销或已过期',403);if(String(e?.message).includes('PERSONAL_STORAGE_BUDGET'))e=new ApiError('STORAGE_BUDGET_EXCEEDED','个人存储预算已满，请保留草稿并稍后重试或删除不用的个人记录',507);if(String(e?.message).includes('MEMBER_LIMIT'))e=new ApiError('LIMIT_EXCEEDED','小队最多50名成员',409);if(String(e?.message).includes('GROUP_STORAGE_BUDGET'))e=new ApiError('STORAGE_BUDGET_EXCEEDED','小队存储预算已满，请保留草稿后重试或删除不用的小队',507);if(String(e?.message).includes('GROUP_COUNT_LIMIT'))e=new ApiError('LIMIT_EXCEEDED','此活动或全站小队数量已达上限',429);const known=e instanceof ApiError||e.name==='ValidationError';const status=e instanceof ApiError?e.status:known?400:503;return new Response(JSON.stringify({error:{code:known?e.code:'SERVICE_UNAVAILABLE',message:known?e.message:'线上暂不可用，请保留草稿后重试',...(known&&e.fields?{fields:e.fields}:{})}}),{status,headers})}}}
