import {it,expect} from 'vitest'
import {readFileSync} from 'node:fs'
import type {ActivityDTO,PersonalPlan} from '../../shared/activity-contract'
import {activityReference,planReference,invitationTarget} from '../../src/online/activity/figma-adapter'
const activity:ActivityDTO={id:'a',revision:1,scheduleRevision:2,spatialRevision:3,status:'published',updatedAt:'2026-10-01T00:00:00Z',eventPackage:JSON.parse(readFileSync('examples/event-minimal.json','utf8'))}
const plan:PersonalPlan={response:{name:'我',presence:[],busy:[{id:'late',source:'manual',date:'2026-10-03',start:'13:52',end:'14:00',title:'接续'},{id:'exact',source:'manual',date:'2026-10-03',start:'13:07',end:'13:52',title:'分钟',note:'本人备注'}],bufferMinutes:5},favorites:[{poiId:'p',visited:false}],routes:[{date:'2026-10-03',stops:[{poiId:'p',visited:false}],spatialRevision:3}]}
it('Figma显示适配保留完整日期和分钟，首尾相接不冲突，收藏路线不生成安排',()=>{const before=JSON.stringify(plan);const v=planReference(activity,plan,'2026-10-03',{dirty:false,offline:false,scheduleRevision:2,spatialRevision:3});expect(v.items.map(x=>x.id)).toEqual(['exact','late']);expect(v.items[0]).toMatchObject({start:'13:07',end:'13:52',durationMinutes:45,conflict:false,state:'saved'});expect(v.items).toHaveLength(2);expect(v.favoriteCount).toBe(1);expect(v.routeCount).toBe(1);expect(JSON.stringify(plan)).toBe(before);expect(activityReference(activity).dates).toEqual(['2026-10-03'])})
it('旧活动版本、未保存及真实离线不能被原型标签伪装已提交',()=>{expect(planReference(activity,plan,'2026-10-03',{dirty:true,offline:true,scheduleRevision:2,spatialRevision:3}).items[0].state).toBe('pending');expect(planReference(activity,plan,'2026-10-03',{dirty:true,offline:false,scheduleRevision:2,spatialRevision:3}).items[0].state).toBe('local');expect(planReference(activity,plan,'2026-10-03',{dirty:false,offline:false,scheduleRevision:1,spatialRevision:3}).items[0].state).toBe('needs_review');const overlap=structuredClone(plan);overlap.response.busy[0].start='13:51';expect(planReference(activity,overlap,'2026-10-03',{dirty:false,offline:false,scheduleRevision:2,spatialRevision:3}).items.every(x=>x.conflict)).toBe(true)})
it('原型加入控件只接受当前站点真实邀请，不把六位码或管理恢复凭据当邀请',()=>{const token='a'.repeat(64);expect(invitationTarget(`https://example.test/groups/abc#invite=${token}`,'https://example.test')).toBe(`/groups/abc#invite=${token}`);for(const value of ['K7Q2M9',`https://other.test/groups/abc#invite=${token}`,`https://example.test/groups/abc#manager=${token}`,`https://example.test/groups/abc#invite=${token}&member=${token}`])expect(()=>invitationTarget(value,'https://example.test')).toThrow()})
it('实际邀请生成器的单一完整date可粘贴并保留，非法日期和权限查询仍拒绝',()=>{const token='a'.repeat(64),base='https://example.test';expect(invitationTarget(`${base}/groups/abc?date=2026-10-05#invite=${token}`,base)).toBe(`/groups/abc?date=2026-10-05#invite=${token}`);for(const query of ['date=2026-02-31','date=2026-13-01','date=10/05','date=2026-10-05&date=2026-10-06','date=2026-10-05&manager='+token,'invite='+token])expect(()=>invitationTarget(`${base}/groups/abc?${query}#invite=${token}`,base)).toThrow()})
