import {expect,it,vi} from 'vitest'
import {prepareOfflineOcr,loadOfflineOcrStatus,type OcrPreparationIO} from '../../src/lib/offline-ocr'
const digest=async(data:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(data))),b=>b.toString(16).padStart(2,'0')).join('')
async function setup(){const files=['tesseract/worker.min.js','tesseract/tesseract-core-simd-lstm.wasm.js','tesseract/chi_sim.traineddata','tesseract/eng.traineddata','assets/ocr-engine-a.js','assets/ocr-recognition-b.js'],resources=await Promise.all(files.map(async path=>({path,sizeBytes:path.length,sha256:await digest(path)}))),manifest={format:1,revision:await digest(JSON.stringify(resources)),resources},storage=new Map<string,Map<string,Response>>();const io:OcrPreparationIO={origin:'https://app.test',base:'/',fetch:vi.fn(async url=>new URL(url).pathname.endsWith('ocr-offline-manifest.json')?new Response(JSON.stringify(manifest)):new Response(new URL(url).pathname.slice(1))),open:async name=>{if(!storage.has(name))storage.set(name,new Map());const cache=storage.get(name)!;return{match:async url=>cache.get(url)?.clone(),put:async(url,response)=>{cache.set(url,response.clone())}}},delete:async name=>storage.delete(name)};return {io,storage,manifest}}
it('explicit preparation validates all engine, runtime, and language bytes before marking ready after restart',async()=>{const t=await setup();expect((await loadOfflineOcrStatus({io:t.io})).state).toBe('unprepared');await prepareOfflineOcr({io:t.io});t.io.fetch=vi.fn(async()=>{throw Error('offline')});expect((await loadOfflineOcrStatus({io:t.io})).state).toBe('ready');expect(t.io.fetch).not.toHaveBeenCalled()})
it('a damaged language resource is rejected and cannot produce a ready marker',async()=>{const t=await setup(),fetch=t.io.fetch;t.io.fetch=async url=>new URL(url).pathname.endsWith('eng.traineddata')?new Response('bad'):fetch(url);await expect(prepareOfflineOcr({io:t.io})).rejects.toThrow('校验');expect((await loadOfflineOcrStatus({io:t.io})).state).toBe('unprepared')})
it('failed replacement retains previous complete prepared OCR cache',async()=>{const t=await setup();const ready=await prepareOfflineOcr({io:t.io});t.io.fetch=async()=>{throw Error('offline')};await expect(prepareOfflineOcr({io:t.io})).rejects.toThrow();expect(await loadOfflineOcrStatus({io:t.io})).toEqual(ready)})
it('deleted or altered cached language is detected after restart instead of claiming ready',async()=>{const t=await setup();await prepareOfflineOcr({io:t.io});const cache=[...t.storage].find(([name])=>name.startsWith('tongye-ocr-resources-'))![1];cache.delete('https://app.test/tesseract/chi_sim.traineddata');expect((await loadOfflineOcrStatus({io:t.io})).state).toBe('incomplete')})
it('incomplete and foreign-origin manifest cannot prepare',async()=>{for(const path of ['https://foreign.test/eng.traineddata','tesseract/missing.traineddata']){const t=await setup();t.manifest.resources[3].path=path;t.manifest.revision=await digest(JSON.stringify(t.manifest.resources));t.io.fetch=async()=>new Response(JSON.stringify(t.manifest));await expect(prepareOfflineOcr({io:t.io})).rejects.toThrow();expect((await loadOfflineOcrStatus({io:t.io})).state).toBe('unprepared')}})
it('a new application build invalidates an older prepared OCR version',async()=>{const t=await setup();await prepareOfflineOcr({io:t.io});const updated=structuredClone(t.manifest);updated.resources[4].sha256='f'.repeat(64);updated.revision=await digest(JSON.stringify(updated.resources));t.io.currentManifest=async()=>updated;expect((await loadOfflineOcrStatus({io:t.io})).state).toBe('incomplete')})
it('quota failure leaves no ready claim and preserves a previous active preparation',async()=>{const t=await setup();await prepareOfflineOcr({io:t.io});const open=t.io.open;t.io.open=async name=>{const cache=await open(name);if(name.startsWith('tongye-ocr-resources-'))return {...cache,put:async()=>{throw new DOMException('quota','QuotaExceededError')}};return cache};await expect(prepareOfflineOcr({io:t.io})).rejects.toThrow('quota');expect((await loadOfflineOcrStatus({io:t.io})).state).toBe('ready')})

it('preparation versioned URLs bypass prior ready caches while stored offline URLs stay canonical',async()=>{const t=await setup(),fetch=t.io.fetch;t.io.fetch=vi.fn(async url=>{const request=new URL(url);if(request.pathname.endsWith('ocr-offline-manifest.json'))expect(request.searchParams.get('ocr-prepare')).toBeTruthy();else expect(request.searchParams.get('ocr-prepare')).toBe(t.manifest.resources.find(resource=>'/'+resource.path===request.pathname)!.sha256);return fetch(url)});await prepareOfflineOcr({io:t.io});const cache=[...t.storage].find(([name])=>name.startsWith('tongye-ocr-resources-'))![1];expect([...cache.keys()].every(url=>new URL(url).search==='')).toBe(true);expect((await loadOfflineOcrStatus({io:t.io})).state).toBe('ready')})

it('a waiting newer build cannot replace the current page preparation or delete its ready resources',async()=>{const t=await setup();Object.assign(t.manifest,{buildId:'a'.repeat(64)});Object.assign(t.io,{currentBuildId:'a'.repeat(64)});const ready=await prepareOfflineOcr({io:t.io}),keys=[...t.storage.keys()],fetch=t.io.fetch,newer={...t.manifest,buildId:'b'.repeat(64)};t.io.fetch=vi.fn(async url=>new URL(url).pathname.endsWith('ocr-offline-manifest.json')?new Response(JSON.stringify(newer)):fetch(url));await expect(prepareOfflineOcr({io:t.io})).rejects.toThrow('请先保存修改并更新应用');expect([...t.storage.keys()]).toEqual(keys);expect(await loadOfflineOcrStatus({io:t.io})).toEqual(ready);expect(t.io.fetch).toHaveBeenCalledTimes(1)})
it('after the page switches builds only a preparation for that running build becomes ready',async()=>{const t=await setup();Object.assign(t.manifest,{buildId:'a'.repeat(64)});Object.assign(t.io,{currentBuildId:'a'.repeat(64)});await prepareOfflineOcr({io:t.io});Object.assign(t.io,{currentBuildId:'b'.repeat(64)});expect((await loadOfflineOcrStatus({io:t.io})).state).toBe('incomplete');Object.assign(t.manifest,{buildId:'b'.repeat(64)});await prepareOfflineOcr({io:t.io});expect((await loadOfflineOcrStatus({io:t.io})).state).toBe('ready');expect([...t.storage.keys()].filter(name=>name.startsWith('tongye-ocr-resources-'))).toHaveLength(1)})
