import {expect,it,vi} from 'vitest'
import {startPublicMap,type PublicMapIO} from '../../src/online/activity/public-map-loading'
import type {ActivityDTO,MediaAssetDTO} from '../../shared/activity-contract'
import type {PreparedActivity} from '../../src/online/activity/offline'
import {readFileSync} from 'node:fs'
const activity=():ActivityDTO=>({id:'e',revision:1,scheduleRevision:1,spatialRevision:1,status:'published',updatedAt:'',eventPackage:JSON.parse(readFileSync('examples/convention-demo.v2.json','utf8'))})
const tick=async()=>{for(let i=0;i<8;i++)await Promise.resolve()}
function setup(){const a=activity();a.eventPackage.event.id=a.id;const m=a.eventPackage.assetManifest![0],release=vi.fn(),prepared:PreparedActivity={activity:a,blobURLs:{'demo-map':'blob:prepared'},status:'ready',preparedAt:'',sizeBytes:1,release},io:PublicMapIO={prepared:async()=>prepared,list:async()=>[{...m,id:'asset',eventId:'e',state:'ready',revision:1} as MediaAssetDTO],fetch:async()=>new Blob(['image']),createURL:()=> 'blob:network',revokeURL:vi.fn()};return {a,prepared,release,io}}
it('matching prepared map appears before a pending network read and survives a failed refresh',async()=>{const t=setup(),show=vi.fn(),notice=vi.fn();let reject!:(error:Error)=>void;t.io.list=()=>new Promise((_,r)=>{reject=r});const stop=startPublicMap(t.a,'demo-map',{show,notice},t.io);await tick();expect(show).toHaveBeenCalledWith('blob:prepared');reject(new Error('network failed'));await tick();expect(show).toHaveBeenCalledTimes(1);expect(notice).toHaveBeenLastCalledWith(expect.stringContaining('已下载地图'));stop.stop();expect(t.release).toHaveBeenCalledTimes(1)})
it('stale or wrong activity snapshots are rejected instead of pairing old image with new coordinates',async()=>{for(const stale of ['stale','wrong-event']){const t=setup();if(stale==='stale')t.prepared.status='stale';else t.prepared.activity={...t.a,id:'other'};t.io.list=async()=>{throw Error('offline')};const show=vi.fn(),stop=startPublicMap(t.a,'demo-map',{show,notice:vi.fn()},t.io);await tick();expect(show).not.toHaveBeenCalled();expect(t.release).toHaveBeenCalledTimes(1);stop.stop()}})
it('a late cached read cannot replace a fresh image; disposed reads release their URLs',async()=>{const t=setup();let resolve!:(p:PreparedActivity)=>void;t.io.prepared=()=>new Promise(r=>{resolve=r});const show=vi.fn(),stop=startPublicMap(t.a,'demo-map',{show,notice:vi.fn()},t.io);await tick();expect(show).toHaveBeenLastCalledWith('blob:network');resolve(t.prepared);await tick();expect(show).toHaveBeenCalledTimes(1);expect(t.release).toHaveBeenCalledTimes(1);stop.stop();expect(t.io.revokeURL).toHaveBeenCalledWith('blob:network')})
it('cleanup aborts active fetch and prevents a previous activity from rendering after navigation',async()=>{const t=setup();let resolve!:(p:PreparedActivity)=>void;t.io.prepared=()=>new Promise(r=>{resolve=r});const show=vi.fn();let signal!:AbortSignal;t.io.list=async(_id,s)=>{signal=s;return new Promise(()=>{})};const stop=startPublicMap(t.a,'demo-map',{show,notice:vi.fn()},t.io);stop.stop();resolve(t.prepared);await tick();expect(signal.aborted).toBe(true);expect(show).not.toHaveBeenCalled();expect(t.release).toHaveBeenCalledTimes(1)})
it('public cache lookup carries the exact complete current package and incompatible online asset is never fetched',async()=>{const t=setup();t.io.prepared=vi.fn(async()=>undefined);t.io.list=async()=>[{...t.a.eventPackage.assetManifest![0],id:'wrong',eventId:'e',state:'ready',revision:1,sha256:'f'.repeat(64)} as MediaAssetDTO];t.io.fetch=vi.fn(t.io.fetch);const notice=vi.fn(),stop=startPublicMap(t.a,'demo-map',{show:vi.fn(),notice},t.io);await tick();expect(t.io.prepared).toHaveBeenCalledWith('e','public',t.a);expect(t.io.fetch).not.toHaveBeenCalled();expect(notice).toHaveBeenCalledWith(expect.stringContaining('地图版本与活动资料不一致'));stop.stop()})
it('an old in-flight image cannot appear beside a newly selected activity package',async()=>{const old=setup(),next=setup();next.a={...next.a,id:'new-event'};next.a.eventPackage.event.id=next.a.id;next.prepared.activity=next.a;next.io.list=()=>new Promise(()=>{});let finish!:(blob:Blob)=>void;old.io.prepared=async()=>undefined;old.io.fetch=()=>new Promise(resolve=>{finish=resolve});const show=vi.fn(),stopOld=startPublicMap(old.a,'demo-map',{show,notice:vi.fn()},old.io);await tick();stopOld.stop();const stopNew=startPublicMap(next.a,'demo-map',{show,notice:vi.fn()},next.io);await tick();finish(new Blob(['old image']));await tick();expect(show).toHaveBeenCalledTimes(1);expect(show).toHaveBeenCalledWith('blob:prepared');expect(old.io.revokeURL).not.toHaveBeenCalled();stopNew.stop()})
it('retry retains a shown validated map through a slow or failed refresh and aborts superseded reads',async()=>{const t=setup(),show=vi.fn(),notice=vi.fn();let reject!:(error:Error)=>void,signal!:AbortSignal;t.io.list=async(_id,s)=>{signal=s;return new Promise((_,r)=>{reject=r})};const controller=startPublicMap(t.a,'demo-map',{show,notice},t.io);await tick();expect(show).toHaveBeenCalledWith('blob:prepared');reject(Error('offline'));await tick();const previousSignal=signal;controller.retry();expect(previousSignal.aborted).toBe(true);await tick();expect(show).toHaveBeenCalledTimes(1);expect(t.release).not.toHaveBeenCalled();reject(Error('still offline'));await tick();expect(show).toHaveBeenCalledTimes(1);expect(t.release).not.toHaveBeenCalled();controller.stop();expect(t.release).toHaveBeenCalledTimes(1)})
it('private activity never reads the public prepared cache, including visibility-only transitions',async()=>{const t=setup();t.a.visibility='private';t.io.prepared=vi.fn(async()=>t.prepared);t.io.list=async()=>{throw Error('no public access')};const show=vi.fn(),controller=startPublicMap(t.a,'demo-map',{show,notice:vi.fn()},t.io);await tick();expect(t.io.prepared).not.toHaveBeenCalled();expect(show).not.toHaveBeenCalled();controller.stop()})
